// External Blockchain/Crypto MCP Integration Registry
// Defines connectable MCP servers and skill providers for the BoredBrain AI agent platform

export interface ExternalIntegration {
  id: string;
  name: string;
  description: string;
  repo: string;
  stars: number;
  npm?: string;
  chains: string[];
  tools: string[];
  toolCount: number;
  category: 'defi' | 'blockchain' | 'trading' | 'marketplace' | 'storage' | 'multi-chain' | 'data' | 'infrastructure';
  status: 'available' | 'coming_soon' | 'beta';
  logo?: string;
  features: string[];
  pricing: 'free' | 'freemium' | 'paid';
  compatibility: ('mcp' | 'a2a' | 'sdk' | 'rest')[];
}

export const EXTERNAL_INTEGRATIONS: ExternalIntegration[] = [
  {
    id: 'bnb-chain-mcp',
    name: 'BNB Chain MCP',
    description:
      'Official BNB Chain MCP server providing blockchain queries, token and NFT operations, wallet management, ERC-8004 autonomous agent registration, and Greenfield decentralized storage access.',
    repo: 'bnb-chain/bnbchain-skills',
    stars: 0,
    npm: '@bnb-chain/mcp',
    chains: ['BNB Chain', 'BSC', 'opBNB', 'Greenfield'],
    tools: [
      'queryBlockNumber',
      'queryTransaction',
      'queryBalance',
      'transferBNB',
      'transferBEP20',
      'deployBEP20',
      'mintNFT',
      'queryNFTMetadata',
      'registerAgent',
      'resolveAgentAddress',
      'greenfieldUpload',
      'greenfieldDownload',
      'greenfieldCreateBucket',
      'walletCreate',
      'walletImport',
      'estimateGas',
    ],
    toolCount: 16,
    category: 'blockchain',
    status: 'available',
    logo: '🟡',
    features: [
      'Full BNB Chain ecosystem access',
      'ERC-8004 autonomous agent registration',
      'Greenfield decentralized storage integration',
      'BEP-20 and BEP-721 token operations',
      'opBNB L2 support for low-cost transactions',
      'Wallet creation and management',
    ],
    pricing: 'free',
    compatibility: ['mcp', 'sdk'],
  },
  {
    id: 'goat-sdk',
    name: 'GOAT SDK',
    description:
      'Multi-chain agentic finance toolkit with 200+ DeFi tools spanning payments, swaps, yield farming, prediction markets, and real-world asset tokenization across all major blockchain ecosystems.',
    repo: 'goat-sdk/goat',
    stars: 965,
    chains: [
      'Ethereum',
      'Polygon',
      'Arbitrum',
      'Optimism',
      'Base',
      'Avalanche',
      'Solana',
      'Aptos',
      'Cosmos',
      'Starknet',
      'BNB Chain',
      'Fantom',
      'Celo',
      'Gnosis',
    ],
    tools: [
      'swap',
      'addLiquidity',
      'removeLiquidity',
      'stake',
      'unstake',
      'claimRewards',
      'bridge',
      'sendPayment',
      'batchTransfer',
      'deployToken',
      'wrapToken',
      'unwrapToken',
      'farmYield',
      'harvestYield',
      'placePrediction',
      'resolvePrediction',
      'tokenizeAsset',
      'fractionalize',
      'getPrice',
      'getPoolInfo',
      'getAPY',
      'getPortfolioValue',
      'approveSpender',
      'revokeApproval',
    ],
    toolCount: 200,
    category: 'defi',
    status: 'available',
    logo: '🐐',
    features: [
      '200+ DeFi tools across major protocols',
      'Multi-chain support spanning EVM, Solana, Aptos, Cosmos, and Starknet',
      'Agentic payments and batch transfers',
      'DEX aggregation and swap routing',
      'Yield farming and staking automation',
      'Prediction market integration',
      'Real-world asset tokenization',
      'Plugin architecture for custom tool extensions',
    ],
    pricing: 'free',
    compatibility: ['mcp', 'sdk', 'rest'],
  },
  {
    id: 'solana-agent-kit',
    name: 'Solana Agent Kit',
    description:
      'Comprehensive Solana action toolkit with 60+ on-chain operations including SPL token management, NFT minting, Jupiter DEX swaps, Raydium and Orca liquidity, and Drift perpetual trading.',
    repo: 'sendaifun/solana-agent-kit',
    stars: 1600,
    chains: ['Solana'],
    tools: [
      'transferSOL',
      'transferSPL',
      'deploySPLToken',
      'mintSPLToken',
      'burnSPLToken',
      'createTokenAccount',
      'mintNFT',
      'mintCompressedNFT',
      'listNFT',
      'cancelNFTListing',
      'buyNFT',
      'jupiterSwap',
      'jupiterLimitOrder',
      'jupiterDCA',
      'raydiumAddLiquidity',
      'raydiumRemoveLiquidity',
      'raydiumSwap',
      'orcaOpenPosition',
      'orcaClosePosition',
      'orcaSwap',
      'driftOpenPerp',
      'driftClosePerp',
      'driftPlaceOrder',
      'driftCancelOrder',
      'stakeSOL',
      'unstakeSOL',
      'requestAirdrop',
      'getBalance',
      'getTokenAccounts',
      'getTransactionHistory',
      'registerDomain',
      'resolveDomain',
    ],
    toolCount: 60,
    category: 'defi',
    status: 'available',
    logo: '☀️',
    features: [
      '60+ native Solana actions',
      'SPL token creation, minting, and transfers',
      'NFT minting including compressed NFTs',
      'Jupiter aggregator swaps, limit orders, and DCA',
      'Raydium AMM liquidity management',
      'Orca concentrated liquidity positions',
      'Drift Protocol perpetual futures trading',
      'SOL staking and domain name registration',
    ],
    pricing: 'free',
    compatibility: ['mcp', 'sdk'],
  },
  {
    id: 'web3-mcp',
    name: 'Web3 MCP',
    description:
      'Multi-chain Web3 MCP server supporting 11 blockchains with balance queries, native and token transfers, Jupiter swaps on Solana, and THORChain cross-chain swaps.',
    repo: 'strangelove-ventures/web3-mcp',
    stars: 93,
    chains: [
      'Solana',
      'Ethereum',
      'Base',
      'Arbitrum',
      'Optimism',
      'Polygon',
      'Avalanche',
      'Bitcoin',
      'TON',
      'XRP',
      'Cosmos',
    ],
    tools: [
      'getBalance',
      'getTokenBalance',
      'transferNative',
      'transferERC20',
      'jupiterSwap',
      'jupiterQuote',
      'thorchainSwap',
      'thorchainQuote',
      'getTransactionStatus',
      'resolveENS',
      'getGasPrice',
    ],
    toolCount: 11,
    category: 'multi-chain',
    status: 'available',
    logo: '🌐',
    features: [
      '11 blockchain networks supported',
      'Unified balance and transfer interface',
      'Jupiter DEX swaps on Solana',
      'THORChain cross-chain swaps',
      'ERC-20 token transfer support',
      'ENS name resolution',
      'Bitcoin and non-EVM chain support',
    ],
    pricing: 'free',
    compatibility: ['mcp'],
  },
  {
    id: 'evm-mcp-server',
    name: 'EVM MCP Server',
    description:
      'Comprehensive EVM MCP server supporting 60+ EVM-compatible chains with 22 tools for smart contract interaction, token operations, ENS resolution, and transaction signing.',
    repo: 'mcpdotdirect/evm-mcp-server',
    stars: 367,
    chains: [
      'Ethereum',
      'Polygon',
      'Arbitrum',
      'Optimism',
      'Base',
      'Avalanche',
      'BNB Chain',
      'Fantom',
      'Gnosis',
      'Celo',
      'Cronos',
      'zkSync',
      'Linea',
      'Scroll',
      'Mantle',
      'Blast',
      'Mode',
      'Moonbeam',
      'Aurora',
      'Metis',
    ],
    tools: [
      'getBalance',
      'getTokenBalance',
      'transferETH',
      'transferERC20',
      'transferERC721',
      'transferERC1155',
      'approveERC20',
      'callContract',
      'readContract',
      'deployContract',
      'getTransactionReceipt',
      'getBlockByNumber',
      'estimateGas',
      'getGasPrice',
      'resolveENS',
      'lookupENS',
      'signMessage',
      'signTransaction',
      'getTokenMetadata',
      'getNFTMetadata',
      'getContractABI',
      'watchContractEvent',
    ],
    toolCount: 22,
    category: 'blockchain',
    status: 'available',
    logo: '⛓️',
    features: [
      '60+ EVM-compatible chains',
      '22 blockchain interaction tools',
      'Smart contract read, write, and deployment',
      'ERC-20, ERC-721, and ERC-1155 token operations',
      'ENS name resolution and reverse lookup',
      'Transaction signing and gas estimation',
      'Contract event monitoring',
      'ABI auto-detection',
    ],
    pricing: 'free',
    compatibility: ['mcp'],
  },
  {
    id: 'tatum-blockchain-mcp',
    name: 'Tatum Blockchain MCP',
    description:
      'Enterprise-grade blockchain data API and RPC gateway covering 130+ networks with tools for block and transaction queries, NFT metadata, wallet portfolios, and address reputation scoring.',
    repo: 'tatumio/blockchain-mcp',
    stars: 14,
    chains: [
      'Ethereum',
      'Polygon',
      'BNB Chain',
      'Solana',
      'Bitcoin',
      'Litecoin',
      'Dogecoin',
      'XRP',
      'Tron',
      'Cardano',
      'Avalanche',
      'Arbitrum',
      'Optimism',
      'Base',
      'Fantom',
      'Celo',
      'Cronos',
      'Algorand',
      'Stellar',
      'Near',
    ],
    tools: [
      'getBlock',
      'getTransaction',
      'getBalance',
      'getTokenBalances',
      'getNFTMetadata',
      'getNFTsByWallet',
      'getWalletPortfolio',
      'getAddressReputation',
      'getTokenPrice',
      'getExchangeRate',
      'getTransactionsByAddress',
      'subscribeToAddress',
      'broadcastTransaction',
      'estimateFee',
    ],
    toolCount: 14,
    category: 'blockchain',
    status: 'available',
    logo: '📊',
    features: [
      '130+ blockchain networks supported',
      'Unified blockchain data API',
      'RPC gateway for direct node access',
      'NFT metadata and ownership queries',
      'Wallet portfolio aggregation',
      'Address reputation and risk scoring',
      'Real-time address subscription webhooks',
      'Fee estimation across chains',
    ],
    pricing: 'freemium',
    compatibility: ['mcp', 'rest'],
  },
  {
    id: 'armor-crypto-mcp',
    name: 'Armor Crypto MCP',
    description:
      'Solana-focused trading MCP server with swap execution, DCA order scheduling, limit order placement, SOL staking, wallet management, and trending token discovery.',
    repo: 'armorwallet/armor-crypto-mcp',
    stars: 191,
    chains: ['Solana'],
    tools: [
      'swapToken',
      'getSwapQuote',
      'placeLimitOrder',
      'cancelLimitOrder',
      'getLimitOrders',
      'createDCAOrder',
      'cancelDCAOrder',
      'getDCAOrders',
      'stakeSOL',
      'unstakeSOL',
      'getStakingInfo',
      'createWallet',
      'importWallet',
      'getWalletBalance',
      'getTokenAccounts',
      'discoverTrending',
      'getTokenInfo',
      'getTokenPrice',
    ],
    toolCount: 18,
    category: 'trading',
    status: 'available',
    logo: '🛡️',
    features: [
      'Solana token swaps with routing',
      'DCA order scheduling and management',
      'Limit order placement and tracking',
      'SOL native staking',
      'Wallet creation and import',
      'Trending token discovery and analysis',
      'Real-time token price feeds',
      'Portfolio balance tracking',
    ],
    pricing: 'free',
    compatibility: ['mcp'],
  },
  {
    id: 'agoragentic',
    name: 'Agoragentic',
    description:
      'Agent-to-agent marketplace enabling autonomous task routing and execution with USDC settlement on Base L2. Supports intent-based discovery and multi-framework agent interoperability.',
    repo: 'rhein1/agoragentic-integrations',
    stars: 6,
    chains: ['Base'],
    tools: [
      'publishIntent',
      'discoverAgents',
      'requestTask',
      'submitResult',
      'settlePayment',
      'getMarketplaceListings',
      'registerAgent',
      'updateAgentProfile',
      'rateAgent',
      'getAgentReputation',
      'createEscrow',
      'releaseEscrow',
    ],
    toolCount: 12,
    category: 'marketplace',
    status: 'beta',
    logo: '🏛️',
    features: [
      'Agent-to-agent task marketplace',
      'Intent-based task routing and discovery',
      'USDC settlement on Base L2',
      'Multi-framework agent support',
      'Escrow-based payment security',
      'Agent reputation and rating system',
      'Autonomous task negotiation',
      'Cross-framework interoperability',
    ],
    pricing: 'freemium',
    compatibility: ['mcp', 'a2a', 'rest'],
  },
  {
    id: 'hyperliquid-mcp',
    name: 'Hyperliquid MCP',
    description:
      'Hyperliquid perpetual futures trading MCP server supporting order placement, position management, account queries, funding rate monitoring, and real-time orderbook streaming on the Hyperliquid L1 DEX.',
    repo: 'caiovicentino/hyperliquid-mcp-server',
    stars: 42,
    chains: ['Hyperliquid', 'Arbitrum'],
    tools: [
      'placeOrder',
      'cancelOrder',
      'cancelAllOrders',
      'getOpenOrders',
      'getPositions',
      'closePosition',
      'setLeverage',
      'getAccountInfo',
      'getFundingRates',
      'getOrderbook',
      'getMarketInfo',
      'getTradeHistory',
      'getTicker',
      'withdrawUSDC',
      'getBalances',
    ],
    toolCount: 15,
    category: 'trading',
    status: 'available',
    logo: '🟢',
    features: [
      'Perpetual futures order placement and management',
      'Position tracking with leverage control',
      'Real-time orderbook and ticker data',
      'Funding rate monitoring',
      'Trade history and account analytics',
      'USDC withdrawal support',
      'Multi-asset perpetual trading',
      'Low-latency L1 DEX execution',
    ],
    pricing: 'free',
    compatibility: ['mcp'],
  },
  {
    id: 'dexpaprika-mcp',
    name: 'DexPaprika MCP',
    description:
      'DEX trading data MCP server powered by CoinPaprika, providing multi-chain DEX pool analytics, token price feeds, OHLCV candle data, liquidity metrics, and top trader tracking.',
    repo: 'coinpaprika/dexpaprika-mcp',
    stars: 28,
    chains: ['Ethereum', 'Solana', 'Base', 'Arbitrum', 'Polygon', 'BNB Chain', 'Avalanche'],
    tools: [
      'getNetworks',
      'getTopDexes',
      'getPoolsByDex',
      'searchPools',
      'getPoolDetails',
      'getPoolOHLCV',
      'getPoolTransactions',
      'getTokenDetails',
      'getTokenPools',
      'getTopPools',
      'getTopMovers',
      'getTokenPrice',
    ],
    toolCount: 12,
    category: 'data',
    status: 'available',
    logo: '📈',
    features: [
      'Multi-chain DEX pool discovery and analytics',
      'OHLCV candlestick data for any pool',
      'Real-time token price feeds',
      'Liquidity depth and volume metrics',
      'Top movers and trending pools',
      'Pool transaction history',
      'Cross-DEX comparison data',
      'No API key required for basic access',
    ],
    pricing: 'freemium',
    compatibility: ['mcp', 'rest'],
  },
  {
    id: 'free-crypto-news',
    name: 'Free Crypto News',
    description:
      'Crypto news aggregation and sentiment analysis MCP server providing headline feeds, article search, sentiment scoring, trending topic detection, and source-level credibility ratings.',
    repo: 'nirholas/free-crypto-news',
    stars: 15,
    chains: [],
    tools: [
      'getLatestNews',
      'searchNews',
      'getSentiment',
      'getTrendingTopics',
      'getNewsByToken',
      'getNewsByCategory',
      'getSourceCredibility',
      'getSentimentTimeline',
    ],
    toolCount: 8,
    category: 'data',
    status: 'available',
    logo: '📰',
    features: [
      'Real-time crypto news aggregation',
      'Article sentiment scoring and classification',
      'Token-specific news filtering',
      'Trending topic detection',
      'Source credibility ratings',
      'Historical sentiment timeline',
      'Category-based news browsing',
      'Free tier with no API key required',
    ],
    pricing: 'free',
    compatibility: ['mcp'],
  },
  {
    id: 'memos-mcp',
    name: 'MemOS',
    description:
      'Agent memory persistence layer providing long-term memory storage, retrieval, and context management for AI agents. Supports structured memory graphs, episodic recall, and cross-session persistence.',
    repo: 'MemTensor/MemOS',
    stars: 310,
    chains: [],
    tools: [
      'storeMemory',
      'recallMemory',
      'searchMemories',
      'deleteMemory',
      'updateMemory',
      'getMemoryGraph',
      'createMemoryCollection',
      'listCollections',
      'getSessionContext',
      'mergeMemories',
    ],
    toolCount: 10,
    category: 'infrastructure',
    status: 'beta',
    logo: '🧠',
    features: [
      'Long-term agent memory persistence',
      'Structured memory graph with relationships',
      'Semantic memory search and retrieval',
      'Episodic recall across sessions',
      'Memory collection organization',
      'Context window management',
      'Memory merging and deduplication',
      'Cross-agent memory sharing',
    ],
    pricing: 'free',
    compatibility: ['mcp', 'sdk'],
  },
  {
    id: 'lightning-mcp',
    name: 'Lightning MCP',
    description:
      'Bitcoin Lightning Network MCP server enabling instant micropayments, invoice creation, payment routing, channel management, and balance queries over the Lightning protocol.',
    repo: 'AbdelStark/lightning-mcp',
    stars: 78,
    chains: ['Bitcoin', 'Lightning Network'],
    tools: [
      'createInvoice',
      'payInvoice',
      'getBalance',
      'getChannels',
      'decodeInvoice',
      'getPaymentStatus',
    ],
    toolCount: 6,
    category: 'blockchain',
    status: 'available',
    logo: '⚡',
    features: [
      'Instant Bitcoin Lightning micropayments',
      'BOLT11 invoice creation and payment',
      'Payment routing and status tracking',
      'Channel balance monitoring',
      'Invoice decoding and validation',
      'Sub-second payment settlement',
    ],
    pricing: 'free',
    compatibility: ['mcp'],
  },
  {
    id: 'base-usdc-transfer',
    name: 'Base USDC Transfer',
    description:
      'Lightweight MCP server for free USDC transfers on Base L2, supporting single and batch transfers, balance queries, and transaction status lookups with gasless relay support.',
    repo: 'magnetai/mcp-free-usdc-transfer',
    stars: 22,
    chains: ['Base'],
    tools: [
      'transferUSDC',
      'batchTransferUSDC',
      'getUSDCBalance',
      'getTransactionStatus',
    ],
    toolCount: 4,
    category: 'defi',
    status: 'available',
    logo: '🔵',
    features: [
      'Free USDC transfers on Base L2',
      'Batch transfer support for multiple recipients',
      'Gasless relay for zero-fee transactions',
      'Real-time transaction status tracking',
    ],
    pricing: 'free',
    compatibility: ['mcp'],
  },
  {
    id: 'marinade-finance-mcp',
    name: 'Marinade Finance MCP',
    description:
      'Marinade Finance liquid staking MCP server for Solana, providing mSOL staking and unstaking, stake account management, validator selection, reward tracking, and native stake conversion.',
    repo: 'lorine93s/marinade-finance-mcp-server',
    stars: 11,
    chains: ['Solana'],
    tools: [
      'stakeSOL',
      'unstakeSOL',
      'getStakeInfo',
      'getmSOLBalance',
      'getValidators',
      'getRewards',
      'convertNativeStake',
      'getAPY',
    ],
    toolCount: 8,
    category: 'defi',
    status: 'available',
    logo: '🌊',
    features: [
      'SOL liquid staking via Marinade',
      'mSOL minting and redemption',
      'Validator performance analytics',
      'Staking reward tracking and history',
      'Native stake account conversion',
      'Real-time APY monitoring',
      'Decentralized validator delegation',
      'Instant unstaking support',
    ],
    pricing: 'free',
    compatibility: ['mcp'],
  },
  {
    id: 'solana-mcp',
    name: 'Solana MCP',
    description:
      'Full-featured Solana MCP server wrapper providing comprehensive RPC access, token operations, NFT management, DeFi interactions, program deployment, and account monitoring across the Solana ecosystem.',
    repo: 'sendaifun/solana-mcp',
    stars: 520,
    chains: ['Solana'],
    tools: [
      'getBalance',
      'getTokenBalance',
      'transferSOL',
      'transferSPL',
      'getTransaction',
      'getBlock',
      'getAccountInfo',
      'getTokenAccounts',
      'createToken',
      'mintToken',
      'burnToken',
      'freezeAccount',
      'thawAccount',
      'mintNFT',
      'getSignaturesForAddress',
      'simulateTransaction',
      'sendTransaction',
      'getProgramAccounts',
      'getSlot',
      'getEpochInfo',
    ],
    toolCount: 20,
    category: 'blockchain',
    status: 'available',
    logo: '🟣',
    features: [
      '20 Solana RPC and interaction tools',
      'SPL token creation, minting, and management',
      'NFT minting via Metaplex',
      'Transaction simulation before submission',
      'Account and program account queries',
      'Block and epoch information access',
      'Token account freeze and thaw operations',
      'Full transaction lifecycle management',
    ],
    pricing: 'free',
    compatibility: ['mcp', 'sdk'],
  },
];

/**
 * Returns all integrations that support a given blockchain.
 * Case-insensitive matching is used.
 */
export function getIntegrationsByChain(chain: string): ExternalIntegration[] {
  const normalized = chain.toLowerCase();
  return EXTERNAL_INTEGRATIONS.filter((integration) =>
    integration.chains.some((c) => c.toLowerCase() === normalized)
  );
}

/**
 * Returns all integrations matching the given category.
 */
export function getIntegrationsByCategory(
  category: ExternalIntegration['category']
): ExternalIntegration[] {
  return EXTERNAL_INTEGRATIONS.filter((integration) => integration.category === category);
}

/**
 * Returns a deduplicated, sorted list of all chains across every integration.
 */
export function getAllChains(): string[] {
  const chainSet = new Set<string>();
  for (const integration of EXTERNAL_INTEGRATIONS) {
    for (const chain of integration.chains) {
      chainSet.add(chain);
    }
  }
  return Array.from(chainSet).sort();
}

/**
 * Finds a single integration by its unique ID, or undefined if not found.
 */
export function getIntegrationById(id: string): ExternalIntegration | undefined {
  return EXTERNAL_INTEGRATIONS.find((integration) => integration.id === id);
}
