/**
 * Mock marketplace listings for development / fallback when DB is empty.
 */

export interface MockMarketplaceListing {
  agentId: string;
  name: string;
  description: string;
  longDescription: string;
  specialization: string;
  tools: string[];
  pricing: { perCall: number; subscription: number | null };
  rating: number;
  reviewCount: number;
  totalCalls: number;
  successRate: number;
  avgResponseTime: number;
  featured: boolean;
  verified: boolean;
  createdAt: string;
  tags: string[];
  developer: { address: string; name: string; agentCount: number };
}

export const MOCK_MARKETPLACE_LISTINGS: MockMarketplaceListing[] = [
  // ── DeFi ──────────────────────────────────────────────
  {
    agentId: 'agent-mkt-001',
    name: 'YieldScout',
    description: 'Finds optimal yield farming strategies across DeFi protocols.',
    longDescription:
      'YieldScout continuously monitors lending rates, LP rewards, and staking yields across 40+ DeFi protocols on Ethereum, Arbitrum, and Base. It evaluates impermanent loss risk, smart-contract audit scores, and TVL trends before recommending positions.',
    specialization: 'defi',
    tools: ['defi-scanner', 'yield-calculator', 'risk-evaluator'],
    pricing: { perCall: 15, subscription: 200 },
    rating: 4.7,
    reviewCount: 134,
    totalCalls: 2870,
    successRate: 96,
    avgResponseTime: 1200,
    featured: true,
    verified: true,
    createdAt: '2025-09-12T08:30:00Z',
    tags: ['yield', 'farming', 'lending', 'arbitrum', 'base'],
    developer: { address: '0x3a1B9c7E42fD6C8A90b5e1D34F72A8bE56c9D0a', name: 'cryptovault.eth', agentCount: 4 },
  },
  {
    agentId: 'agent-mkt-002',
    name: 'LiquidityGuard',
    description: 'Monitors liquidity pool health and alerts on rug-pull signals.',
    longDescription:
      'LiquidityGuard watches on-chain liquidity changes, ownership renounce status, and token holder concentration in real time. Sends configurable alerts when any tracked pool shows warning signals such as sudden LP withdrawals or mint-function abuse.',
    specialization: 'defi',
    tools: ['pool-monitor', 'token-scanner', 'alert-dispatcher'],
    pricing: { perCall: 10, subscription: 150 },
    rating: 4.5,
    reviewCount: 89,
    totalCalls: 1950,
    successRate: 94,
    avgResponseTime: 800,
    featured: false,
    verified: true,
    createdAt: '2025-10-03T14:15:00Z',
    tags: ['liquidity', 'rug-pull', 'security', 'alerts', 'pools'],
    developer: { address: '0x7F2c9bA8D3E14567aBC0d8E91F23456789AbCdEf', name: 'shieldops', agentCount: 2 },
  },
  {
    agentId: 'agent-mkt-003',
    name: 'BridgeOptimizer',
    description: 'Finds the cheapest and fastest cross-chain bridge route.',
    longDescription:
      'Compares fees, slippage, and estimated confirmation times across all major bridges (Stargate, Across, Hop, Synapse, LayerZero) and returns a ranked list of routes. Supports 12 chains including Ethereum, Polygon, Arbitrum, Optimism, Base, and zkSync.',
    specialization: 'defi',
    tools: ['bridge-aggregator', 'gas-estimator', 'route-optimizer'],
    pricing: { perCall: 8, subscription: null },
    rating: 4.3,
    reviewCount: 56,
    totalCalls: 1340,
    successRate: 91,
    avgResponseTime: 1500,
    featured: false,
    verified: true,
    createdAt: '2025-11-18T10:00:00Z',
    tags: ['bridge', 'cross-chain', 'gas', 'multichain'],
    developer: { address: '0xAaBbCc1234567890dDeEfF0011223344556677Aa', name: 'bridgelabs.eth', agentCount: 1 },
  },

  // ── Market Analysis ───────────────────────────────────
  {
    agentId: 'agent-mkt-004',
    name: 'WhaleTracker',
    description: 'Tracks large wallet movements and surfaces actionable signals.',
    longDescription:
      'WhaleTracker monitors the top 500 wallets by holdings for each tracked token, detects unusual transfer patterns, and correlates them with DEX order flow. Results are delivered as concise market-impact summaries with confidence scores.',
    specialization: 'market',
    tools: ['wallet-tracker', 'dex-analyzer', 'signal-scorer'],
    pricing: { perCall: 20, subscription: 350 },
    rating: 4.8,
    reviewCount: 147,
    totalCalls: 2650,
    successRate: 97,
    avgResponseTime: 950,
    featured: true,
    verified: true,
    createdAt: '2025-08-22T06:45:00Z',
    tags: ['whales', 'wallets', 'signals', 'on-chain', 'dex'],
    developer: { address: '0x1234AbCd5678Ef0890124aBC3456de0f78901234', name: 'deepflow', agentCount: 3 },
  },
  {
    agentId: 'agent-mkt-005',
    name: 'SentimentPulse',
    description: 'Aggregates social sentiment from Twitter, Discord, and Farcaster.',
    longDescription:
      'SentimentPulse ingests posts from crypto Twitter, top Discord alpha groups, and Farcaster channels. It runs NLP sentiment analysis and produces a composite mood score per token, along with trending narrative detection and influencer activity heatmaps.',
    specialization: 'market',
    tools: ['social-scraper', 'nlp-analyzer', 'trend-detector'],
    pricing: { perCall: 12, subscription: null },
    rating: 4.2,
    reviewCount: 73,
    totalCalls: 1620,
    successRate: 89,
    avgResponseTime: 1800,
    featured: false,
    verified: true,
    createdAt: '2025-10-30T12:20:00Z',
    tags: ['sentiment', 'twitter', 'discord', 'farcaster', 'nlp'],
    developer: { address: '0xBbCcDd2345678901eEfFaA1122334455667788Bb', name: 'pulsemetrics', agentCount: 2 },
  },
  {
    agentId: 'agent-mkt-006',
    name: 'TechChartist',
    description: 'Generates technical analysis reports with chart pattern detection.',
    longDescription:
      'TechChartist applies classical and modern TA indicators (RSI, MACD, Bollinger Bands, Ichimoku, volume profile) to any token pair. It detects chart patterns (head-and-shoulders, double bottoms, wedges) and produces trade setup suggestions with entry/exit zones.',
    specialization: 'market',
    tools: ['chart-analyzer', 'pattern-detector', 'indicator-engine'],
    pricing: { perCall: 18, subscription: 250 },
    rating: 4.4,
    reviewCount: 98,
    totalCalls: 2210,
    successRate: 92,
    avgResponseTime: 1100,
    featured: false,
    verified: true,
    createdAt: '2025-09-05T09:10:00Z',
    tags: ['technical-analysis', 'charts', 'patterns', 'trading'],
    developer: { address: '0xCcDdEe3456789012fFaAbB2233445566778899Cc', name: 'chartforge', agentCount: 5 },
  },

  // ── Research ──────────────────────────────────────────
  {
    agentId: 'agent-mkt-007',
    name: 'TokenIntel',
    description: 'Deep-dives into tokenomics, team backgrounds, and roadmap viability.',
    longDescription:
      'TokenIntel produces comprehensive research reports covering supply mechanics, vesting schedules, governance structure, team LinkedIn verification, GitHub commit activity, and competitive landscape analysis. Each report includes a proprietary "Conviction Score" from 0-100.',
    specialization: 'research',
    tools: ['tokenomics-parser', 'team-verifier', 'github-analyzer'],
    pricing: { perCall: 35, subscription: 500 },
    rating: 4.9,
    reviewCount: 112,
    totalCalls: 1890,
    successRate: 98,
    avgResponseTime: 2400,
    featured: true,
    verified: true,
    createdAt: '2025-07-15T11:00:00Z',
    tags: ['research', 'tokenomics', 'due-diligence', 'fundamentals'],
    developer: { address: '0xDdEeFf4567890123aAbBcC3344556677889900Dd', name: 'labyrinth.research', agentCount: 3 },
  },
  {
    agentId: 'agent-mkt-008',
    name: 'GovWatch',
    description: 'Tracks DAO governance proposals and voting patterns.',
    longDescription:
      'GovWatch indexes Snapshot and on-chain governance proposals across 80+ DAOs. It summarizes proposal content, predicts outcomes based on historical delegate behavior, and highlights contentious votes that could impact token price.',
    specialization: 'research',
    tools: ['snapshot-indexer', 'vote-analyzer', 'proposal-summarizer'],
    pricing: { perCall: 10, subscription: null },
    rating: 4.1,
    reviewCount: 34,
    totalCalls: 680,
    successRate: 93,
    avgResponseTime: 1300,
    featured: false,
    verified: true,
    createdAt: '2025-12-01T15:30:00Z',
    tags: ['governance', 'dao', 'snapshot', 'voting', 'proposals'],
    developer: { address: '0xEeFfAa5678901234bBcCdD4455667788990011Ee', name: 'govnerd', agentCount: 1 },
  },

  // ── News ──────────────────────────────────────────────
  {
    agentId: 'agent-mkt-009',
    name: 'CryptoDigest',
    description: 'Curates the top crypto news stories and delivers concise briefs.',
    longDescription:
      'CryptoDigest pulls from 50+ news sources (CoinDesk, The Block, Decrypt, DL News, etc.), de-duplicates stories, and produces ranked daily briefs or on-demand topic summaries. Includes relevance scoring and market-impact estimates for each story.',
    specialization: 'news',
    tools: ['news-aggregator', 'dedup-engine', 'summary-writer'],
    pricing: { perCall: 5, subscription: 100 },
    rating: 4.6,
    reviewCount: 88,
    totalCalls: 2990,
    successRate: 99,
    avgResponseTime: 600,
    featured: true,
    verified: true,
    createdAt: '2025-08-01T07:00:00Z',
    tags: ['news', 'briefing', 'aggregation', 'daily-digest'],
    developer: { address: '0xFfAaBb6789012345cCdDeE5566778899001122Ff', name: 'newsflow.xyz', agentCount: 2 },
  },
  {
    agentId: 'agent-mkt-010',
    name: 'RegRadar',
    description: 'Monitors global crypto regulation updates and compliance changes.',
    longDescription:
      'RegRadar tracks regulatory filings, court rulings, and legislative proposals from the SEC, CFTC, MiCA, and 30+ other jurisdictions. It flags changes relevant to DeFi protocols, stablecoins, and token classifications and provides plain-English summaries.',
    specialization: 'news',
    tools: ['regulation-crawler', 'legal-summarizer', 'jurisdiction-mapper'],
    pricing: { perCall: 15, subscription: null },
    rating: 4.3,
    reviewCount: 41,
    totalCalls: 520,
    successRate: 95,
    avgResponseTime: 1700,
    featured: false,
    verified: true,
    createdAt: '2025-11-10T13:45:00Z',
    tags: ['regulation', 'compliance', 'sec', 'mica', 'legal'],
    developer: { address: '0xAa1122Bb3344Cc5566Dd7788Ee9900Ff0011AaBb', name: 'compliancenode', agentCount: 1 },
  },

  // ── Security ──────────────────────────────────────────
  {
    agentId: 'agent-mkt-011',
    name: 'AuditLens',
    description: 'Scans smart contracts for common vulnerabilities and code smells.',
    longDescription:
      'AuditLens performs static analysis on Solidity contracts, checking for reentrancy, unchecked external calls, integer overflows, access-control gaps, and 60+ other vulnerability patterns. Returns findings ranked by severity with remediation suggestions.',
    specialization: 'security',
    tools: ['solidity-analyzer', 'vuln-scanner', 'report-generator'],
    pricing: { perCall: 40, subscription: null },
    rating: 4.6,
    reviewCount: 67,
    totalCalls: 890,
    successRate: 97,
    avgResponseTime: 2200,
    featured: false,
    verified: true,
    createdAt: '2025-09-20T16:00:00Z',
    tags: ['audit', 'security', 'solidity', 'vulnerabilities', 'smart-contracts'],
    developer: { address: '0xBb2233Cc4455Dd6677Ee8899Ff0011Aa2233BbCc', name: 'fortressec', agentCount: 3 },
  },
  {
    agentId: 'agent-mkt-012',
    name: 'PhishGuard',
    description: 'Detects phishing links and malicious contract approvals.',
    longDescription:
      'PhishGuard maintains a real-time database of known phishing domains, drainer contracts, and malicious approval patterns. Users can submit URLs or contract addresses for instant risk assessment, and receive a detailed threat breakdown.',
    specialization: 'security',
    tools: ['url-scanner', 'approval-checker', 'threat-db'],
    pricing: { perCall: 5, subscription: null },
    rating: 4.8,
    reviewCount: 102,
    totalCalls: 2450,
    successRate: 99,
    avgResponseTime: 350,
    featured: true,
    verified: true,
    createdAt: '2025-08-10T04:20:00Z',
    tags: ['phishing', 'security', 'approvals', 'scam-detection'],
    developer: { address: '0xCc3344Dd5566Ee7788Ff9900Aa1122Bb3344CcDd', name: 'shieldwall.eth', agentCount: 2 },
  },

  // ── NFT ───────────────────────────────────────────────
  {
    agentId: 'agent-mkt-013',
    name: 'FloorSweep',
    description: 'Tracks NFT collection floor prices and identifies undervalued listings.',
    longDescription:
      'FloorSweep monitors OpenSea, Blur, and Magic Eden for floor price changes across 500+ collections. It identifies trait-based undervaluations, alerts on sudden floor drops, and provides collection momentum scores based on volume and unique buyer trends.',
    specialization: 'nft',
    tools: ['nft-indexer', 'trait-analyzer', 'price-tracker'],
    pricing: { perCall: 10, subscription: null },
    rating: 4.0,
    reviewCount: 45,
    totalCalls: 1100,
    successRate: 90,
    avgResponseTime: 900,
    featured: false,
    verified: false,
    createdAt: '2025-10-15T19:30:00Z',
    tags: ['nft', 'floor-price', 'opensea', 'blur', 'collections'],
    developer: { address: '0xDd4455Ee6677Ff8899Aa0011Bb2233Cc4455DdEe', name: 'nftgrinder', agentCount: 1 },
  },
  {
    agentId: 'agent-mkt-014',
    name: 'MintRadar',
    description: 'Discovers upcoming NFT mints and evaluates hype and team legitimacy.',
    longDescription:
      'MintRadar scans Twitter, Discord announcements, and on-chain deploy events to surface upcoming mints before they trend. Each mint is scored on team credibility, art quality, community size, and smart-contract safety.',
    specialization: 'nft',
    tools: ['mint-scanner', 'hype-scorer', 'contract-checker'],
    pricing: { perCall: 8, subscription: null },
    rating: 3.8,
    reviewCount: 28,
    totalCalls: 540,
    successRate: 86,
    avgResponseTime: 1400,
    featured: false,
    verified: false,
    createdAt: '2025-12-05T21:00:00Z',
    tags: ['nft', 'minting', 'alpha', 'discovery'],
    developer: { address: '0xEe5566Ff7788Aa9900Bb1122Cc3344Dd5566EeFf', name: 'mintoor', agentCount: 1 },
  },

  // ── Gaming ────────────────────────────────────────────
  {
    agentId: 'agent-mkt-015',
    name: 'GuildManager',
    description: 'Optimizes Web3 gaming guild operations and scholarship distribution.',
    longDescription:
      'GuildManager helps gaming guilds track scholar performance, distribute earnings fairly, and identify the most profitable games. It integrates with Axie Infinity, Pixels, Big Time, and 10+ other blockchain games via their APIs.',
    specialization: 'gaming',
    tools: ['guild-tracker', 'earnings-splitter', 'game-api-hub'],
    pricing: { perCall: 12, subscription: 180 },
    rating: 3.9,
    reviewCount: 22,
    totalCalls: 380,
    successRate: 88,
    avgResponseTime: 1600,
    featured: false,
    verified: false,
    createdAt: '2025-11-25T08:15:00Z',
    tags: ['gaming', 'guild', 'scholarship', 'play-to-earn'],
    developer: { address: '0xFf6677Aa8899Bb0011Cc2233Dd4455Ee6677FfAa', name: 'guildmaster.gg', agentCount: 2 },
  },
  {
    agentId: 'agent-mkt-016',
    name: 'LootOracle',
    description: 'Prices in-game items and suggests optimal trade windows.',
    longDescription:
      'LootOracle tracks in-game asset prices across major blockchain gaming marketplaces. It applies historical price analysis to predict short-term trends and recommends buy/sell timing for rare items, land plots, and consumables.',
    specialization: 'gaming',
    tools: ['item-pricer', 'marketplace-scraper', 'trend-predictor'],
    pricing: { perCall: 7, subscription: null },
    rating: 3.7,
    reviewCount: 15,
    totalCalls: 230,
    successRate: 85,
    avgResponseTime: 1100,
    featured: false,
    verified: false,
    createdAt: '2026-01-08T17:40:00Z',
    tags: ['gaming', 'loot', 'items', 'marketplace', 'pricing'],
    developer: { address: '0xAa7788Bb9900Cc1122Dd3344Ee5566Ff7788AaBb', name: 'lootlabs', agentCount: 1 },
  },

  // ── Education ─────────────────────────────────────────
  {
    agentId: 'agent-mkt-017',
    name: 'SolidityTutor',
    description: 'Interactive Solidity learning assistant with exercises and code review.',
    longDescription:
      'SolidityTutor provides structured lessons from beginner to advanced Solidity development. It offers coding exercises, reviews submitted contracts, explains gas optimizations, and quizzes users on security best practices. Tracks learning progress across sessions.',
    specialization: 'education',
    tools: ['lesson-engine', 'code-reviewer', 'quiz-generator'],
    pricing: { perCall: 5, subscription: 100 },
    rating: 4.7,
    reviewCount: 63,
    totalCalls: 1750,
    successRate: 99,
    avgResponseTime: 500,
    featured: false,
    verified: true,
    createdAt: '2025-10-01T10:30:00Z',
    tags: ['education', 'solidity', 'learning', 'smart-contracts', 'coding'],
    developer: { address: '0xBb8899Cc0011Dd2233Ee4455Ff6677Aa8899BbCc', name: 'learnchain.dev', agentCount: 4 },
  },
  {
    agentId: 'agent-mkt-018',
    name: 'DeFiExplainer',
    description: 'Breaks down complex DeFi concepts into beginner-friendly explanations.',
    longDescription:
      'DeFiExplainer answers questions about any DeFi protocol, mechanism, or term in plain language. It can walk through specific transactions to show how protocols work under the hood, and provides visual diagrams of token flows.',
    specialization: 'education',
    tools: ['concept-mapper', 'tx-decoder', 'diagram-generator'],
    pricing: { perCall: 5, subscription: null },
    rating: 4.5,
    reviewCount: 48,
    totalCalls: 1280,
    successRate: 97,
    avgResponseTime: 700,
    featured: false,
    verified: true,
    createdAt: '2025-11-12T09:00:00Z',
    tags: ['education', 'defi', 'explainer', 'beginner', 'tutorials'],
    developer: { address: '0xCc9900Dd1122Ee3344Ff5566Aa7788Bb9900CcDd', name: 'learnchain.dev', agentCount: 4 },
  },

  // ── Health ────────────────────────────────────────────
  {
    agentId: 'agent-mkt-019',
    name: 'WellnessOracle',
    description: 'Provides personalized wellness tips based on on-chain activity patterns.',
    longDescription:
      'WellnessOracle analyzes a wallet\'s transaction timestamps to detect unhealthy trading patterns (sleep-deprived trading, revenge trading after losses, excessive screen time). It offers evidence-based wellness suggestions and can set "cool-down" reminders.',
    specialization: 'health',
    tools: ['activity-analyzer', 'pattern-detector', 'reminder-scheduler'],
    pricing: { perCall: 5, subscription: null },
    rating: 4.1,
    reviewCount: 19,
    totalCalls: 310,
    successRate: 93,
    avgResponseTime: 450,
    featured: false,
    verified: false,
    createdAt: '2026-01-15T14:00:00Z',
    tags: ['health', 'wellness', 'mindfulness', 'trading-habits'],
    developer: { address: '0xDd0011Ee2233Ff4455Aa6677Bb8899Cc0011DdEe', name: 'zentrader', agentCount: 1 },
  },

  // ── Legal ─────────────────────────────────────────────
  {
    agentId: 'agent-mkt-020',
    name: 'TaxHelper',
    description: 'Generates preliminary crypto tax reports from on-chain history.',
    longDescription:
      'TaxHelper ingests wallet addresses, traces all swaps, bridges, staking rewards, and airdrops, and categorizes each event by tax treatment (capital gains, income, etc.). Exports CSV reports compatible with TurboTax, Koinly, and CoinTracker.',
    specialization: 'legal',
    tools: ['tx-classifier', 'cost-basis-calculator', 'csv-exporter'],
    pricing: { perCall: 25, subscription: 300 },
    rating: 4.4,
    reviewCount: 77,
    totalCalls: 1560,
    successRate: 94,
    avgResponseTime: 2500,
    featured: false,
    verified: true,
    createdAt: '2025-09-28T11:30:00Z',
    tags: ['tax', 'legal', 'reporting', 'accounting', 'compliance'],
    developer: { address: '0xEe1122Ff3344Aa5566Bb7788Cc9900Dd1122EeFf', name: 'taxnodes', agentCount: 2 },
  },

  // ── Media / Creative ──────────────────────────────────
  {
    agentId: 'agent-mkt-021',
    name: 'NFTArtGen',
    description: 'Generates trait-based generative art collections from text prompts.',
    longDescription:
      'NFTArtGen creates layered generative art suitable for PFP collections. Users describe styles, color palettes, and trait categories; the agent produces sample outputs and full collection metadata. Supports ERC-721 and ERC-1155 metadata standards.',
    specialization: 'creative',
    tools: ['art-generator', 'trait-combiner', 'metadata-builder'],
    pricing: { perCall: 30, subscription: null },
    rating: 4.2,
    reviewCount: 36,
    totalCalls: 470,
    successRate: 91,
    avgResponseTime: 2300,
    featured: false,
    verified: false,
    createdAt: '2025-12-20T18:00:00Z',
    tags: ['creative', 'generative-art', 'nft', 'pfp', 'collections'],
    developer: { address: '0xFf2233Aa4455Bb6677Cc8899Dd0011Ee2233FfAa', name: 'pixelalchemy', agentCount: 1 },
  },
  {
    agentId: 'agent-mkt-022',
    name: 'ThreadCraft',
    description: 'Drafts engaging crypto Twitter threads from research notes.',
    longDescription:
      'ThreadCraft takes raw research notes, data points, or article links and transforms them into well-structured Twitter/X threads optimized for engagement. It suggests hook tweets, adds relevant emojis and formatting, and recommends posting times based on follower timezone analysis.',
    specialization: 'media',
    tools: ['thread-writer', 'engagement-optimizer', 'schedule-advisor'],
    pricing: { perCall: 8, subscription: null },
    rating: 4.0,
    reviewCount: 52,
    totalCalls: 980,
    successRate: 96,
    avgResponseTime: 800,
    featured: false,
    verified: false,
    createdAt: '2025-11-05T20:15:00Z',
    tags: ['media', 'twitter', 'threads', 'content', 'marketing'],
    developer: { address: '0xAa3344Bb5566Cc7788Dd9900Ee1122Ff3344AaBb', name: 'viralnode', agentCount: 2 },
  },

  // ── Utility ───────────────────────────────────────────
  {
    agentId: 'agent-mkt-023',
    name: 'GasOracle',
    description: 'Predicts optimal gas prices and recommends transaction timing.',
    longDescription:
      'GasOracle uses historical block data and mempool analysis to predict gas prices 1-30 minutes ahead. It recommends optimal submission times for non-urgent transactions and can estimate costs for complex contract interactions.',
    specialization: 'utility',
    tools: ['gas-predictor', 'mempool-analyzer', 'cost-estimator'],
    pricing: { perCall: 5, subscription: null },
    rating: 4.5,
    reviewCount: 131,
    totalCalls: 2800,
    successRate: 95,
    avgResponseTime: 200,
    featured: false,
    verified: true,
    createdAt: '2025-08-18T05:00:00Z',
    tags: ['gas', 'utility', 'optimization', 'ethereum', 'transactions'],
    developer: { address: '0xBb4455Cc6677Dd8899Ee0011Ff2233Aa4455BbCc', name: 'gasworks.eth', agentCount: 1 },
  },
  {
    agentId: 'agent-mkt-024',
    name: 'ENSResolver',
    description: 'Resolves ENS names, checks availability, and suggests alternatives.',
    longDescription:
      'ENSResolver provides instant ENS name lookups, availability checks, and registration cost estimates. It can suggest similar available names when a desired name is taken, and tracks expiring premium names that may become available soon.',
    specialization: 'utility',
    tools: ['ens-lookup', 'name-suggester', 'expiry-tracker'],
    pricing: { perCall: 5, subscription: null },
    rating: 4.3,
    reviewCount: 39,
    totalCalls: 920,
    successRate: 98,
    avgResponseTime: 300,
    featured: false,
    verified: true,
    createdAt: '2025-10-22T12:00:00Z',
    tags: ['ens', 'domains', 'naming', 'utility', 'identity'],
    developer: { address: '0xCc5566Dd7788Ee9900Ff1122Aa3344Bb5566CcDd', name: 'namesmith', agentCount: 1 },
  },
  {
    agentId: 'agent-mkt-025',
    name: 'PortfolioLens',
    description: 'Aggregates multi-chain portfolio balances into a unified dashboard view.',
    longDescription:
      'PortfolioLens connects to 15+ chains and aggregates token balances, NFT holdings, DeFi positions, and unclaimed airdrops into a single view. It calculates historical PnL, tracks cost basis, and highlights concentration risks.',
    specialization: 'utility',
    tools: ['multi-chain-indexer', 'portfolio-tracker', 'pnl-calculator'],
    pricing: { perCall: 10, subscription: 150 },
    rating: 4.6,
    reviewCount: 85,
    totalCalls: 2100,
    successRate: 93,
    avgResponseTime: 1400,
    featured: false,
    verified: true,
    createdAt: '2025-09-15T08:00:00Z',
    tags: ['portfolio', 'tracking', 'multi-chain', 'pnl', 'dashboard'],
    developer: { address: '0xDd6677Ee8899Ff0011Aa2233Bb4455Cc6677DdEe', name: 'folioworks', agentCount: 2 },
  },

  // ── Additional diverse agents ─────────────────────────
  {
    agentId: 'agent-mkt-026',
    name: 'AirdropHunter',
    description: 'Identifies potential airdrop opportunities and eligibility criteria.',
    longDescription:
      'AirdropHunter monitors protocol activity, testnet launches, and governance participation across emerging projects to predict likely airdrop campaigns. It checks wallet eligibility against known criteria and suggests actions to qualify for upcoming drops.',
    specialization: 'research',
    tools: ['protocol-scanner', 'eligibility-checker', 'action-planner'],
    pricing: { perCall: 15, subscription: null },
    rating: 4.1,
    reviewCount: 94,
    totalCalls: 1870,
    successRate: 87,
    avgResponseTime: 1000,
    featured: false,
    verified: false,
    createdAt: '2025-10-08T16:30:00Z',
    tags: ['airdrops', 'alpha', 'eligibility', 'farming'],
    developer: { address: '0xEe7788Ff9900Aa1122Bb3344Cc5566Dd7788EeFf', name: 'dropzone', agentCount: 3 },
  },
  {
    agentId: 'agent-mkt-027',
    name: 'MEVShield',
    description: 'Protects transactions from MEV extraction and sandwich attacks.',
    longDescription:
      'MEVShield analyzes pending transactions for sandwich attack vulnerability, recommends optimal slippage settings, and can route transactions through private mempools (Flashbots Protect, MEV Blocker) to prevent frontrunning.',
    specialization: 'security',
    tools: ['mev-analyzer', 'private-tx-router', 'slippage-optimizer'],
    pricing: { perCall: 10, subscription: null },
    rating: 4.5,
    reviewCount: 58,
    totalCalls: 1340,
    successRate: 96,
    avgResponseTime: 250,
    featured: false,
    verified: true,
    createdAt: '2025-09-30T07:15:00Z',
    tags: ['mev', 'security', 'frontrunning', 'flashbots', 'protection'],
    developer: { address: '0xFf8899Aa0011Bb2233Cc4455Dd6677Ee8899FfAa', name: 'darkforest.dev', agentCount: 2 },
  },
  {
    agentId: 'agent-mkt-028',
    name: 'StableScan',
    description: 'Monitors stablecoin peg health and reserve transparency.',
    longDescription:
      'StableScan tracks peg deviations across all major stablecoins (USDC, USDT, DAI, FRAX, GHO, etc.) on CEX and DEX venues. It monitors reserve attestation reports, flags custody risks, and sends alerts when depeg events exceed configurable thresholds.',
    specialization: 'defi',
    tools: ['peg-monitor', 'reserve-tracker', 'depeg-alerter'],
    pricing: { perCall: 8, subscription: null },
    rating: 4.4,
    reviewCount: 42,
    totalCalls: 760,
    successRate: 98,
    avgResponseTime: 400,
    featured: false,
    verified: true,
    createdAt: '2025-11-28T13:00:00Z',
    tags: ['stablecoins', 'defi', 'peg', 'reserves', 'monitoring'],
    developer: { address: '0xAaBb0011CcDd2233EeFf4455667788990011AaBb', name: 'pegwatch', agentCount: 1 },
  },
  {
    agentId: 'agent-mkt-029',
    name: 'ContractDeployer',
    description: 'Assists with deploying and verifying smart contracts across chains.',
    longDescription:
      'ContractDeployer guides users through contract deployment on any EVM chain. It handles constructor arguments, deterministic deployments via CREATE2, source verification on block explorers, and proxy pattern setup (UUPS, Transparent). Supports Hardhat and Foundry project formats.',
    specialization: 'utility',
    tools: ['deploy-helper', 'verifier', 'proxy-setup'],
    pricing: { perCall: 20, subscription: null },
    rating: 4.3,
    reviewCount: 31,
    totalCalls: 420,
    successRate: 92,
    avgResponseTime: 1900,
    featured: false,
    verified: false,
    createdAt: '2025-12-10T10:45:00Z',
    tags: ['deployment', 'smart-contracts', 'verification', 'utility', 'evm'],
    developer: { address: '0xBbCc1122DdEe3344FfAa55667788990011BbCc22', name: 'deployoor', agentCount: 1 },
  },
  {
    agentId: 'agent-mkt-030',
    name: 'AlphaStream',
    description: 'Real-time on-chain alpha feed with configurable signal filters.',
    longDescription:
      'AlphaStream surfaces unusual on-chain activity in real time: large token unlocks, whale accumulation, new liquidity pool creation, governance attacks, and contract upgrades. Users configure signal types and minimum impact thresholds to reduce noise.',
    specialization: 'market',
    tools: ['chain-listener', 'signal-filter', 'alert-engine'],
    pricing: { perCall: 25, subscription: 400 },
    rating: 4.7,
    reviewCount: 69,
    totalCalls: 1430,
    successRate: 93,
    avgResponseTime: 350,
    featured: false,
    verified: true,
    createdAt: '2025-10-18T06:00:00Z',
    tags: ['alpha', 'signals', 'on-chain', 'real-time', 'alerts'],
    developer: { address: '0xCcDd2233EeFf4455AaBb66778899001122CcDd33', name: 'alphaforge', agentCount: 3 },
  },

  // ═══════════════════════════════════════════════════════
  // NEW AGENTS (031–080+)
  // ═══════════════════════════════════════════════════════

  // ── DeFi (expanded) ───────────────────────────────────
  {
    agentId: 'agent-mkt-031',
    name: 'DEXAggregatorPro',
    description: 'Finds the best swap route across 60+ DEXs with MEV-protected execution.',
    longDescription:
      'DEXAggregatorPro splits orders across Uniswap, Curve, Balancer, SushiSwap, and 55+ other venues to minimize slippage. It accounts for gas costs, price impact, and routing through intermediate tokens. Supports limit orders and TWAP execution strategies.',
    specialization: 'defi',
    tools: ['dex-router', 'price-aggregator', 'order-splitter'],
    pricing: { perCall: 6, subscription: null },
    rating: 4.6,
    reviewCount: 118,
    totalCalls: 8920,
    successRate: 97,
    avgResponseTime: 450,
    featured: true,
    verified: true,
    createdAt: '2025-08-15T09:00:00Z',
    tags: ['dex', 'swap', 'aggregator', 'routing'],
    developer: { address: '0xAa1234Bb5678Cc9012Dd3456Ee7890Ff1234AaBb', name: 'routemax.eth', agentCount: 3 },
  },
  {
    agentId: 'agent-mkt-032',
    name: 'LendingOptimizer',
    description: 'Maximizes lending yields by shifting deposits across Aave, Compound, and Morpho.',
    longDescription:
      'LendingOptimizer monitors supply and borrow APYs across all major lending protocols in real time. It recommends optimal deposit allocation, identifies the cheapest borrowing venues, and alerts users when rate differentials create profitable rebalancing opportunities.',
    specialization: 'defi',
    tools: ['lending-monitor', 'rate-comparator', 'rebalance-engine'],
    pricing: { perCall: 8, subscription: 120 },
    rating: 4.4,
    reviewCount: 76,
    totalCalls: 3410,
    successRate: 95,
    avgResponseTime: 700,
    featured: false,
    verified: true,
    createdAt: '2025-09-22T11:30:00Z',
    tags: ['lending', 'aave', 'compound', 'optimization'],
    developer: { address: '0xBb2345Cc6789Dd0123Ee4567Ff8901Aa2345BbCc', name: 'lendwise', agentCount: 2 },
  },
  {
    agentId: 'agent-mkt-033',
    name: 'ILCalculator',
    description: 'Calculates impermanent loss for any LP position with historical backtesting.',
    longDescription:
      'ILCalculator provides precise impermanent loss calculations for concentrated and full-range liquidity positions. It backtests historical price movements to show what your IL would have been over any timeframe, and projects future IL scenarios using volatility models.',
    specialization: 'defi',
    tools: ['il-calculator', 'price-fetcher', 'backtest-engine'],
    pricing: { perCall: 3, subscription: null },
    rating: 4.2,
    reviewCount: 53,
    totalCalls: 2180,
    successRate: 98,
    avgResponseTime: 500,
    featured: false,
    verified: true,
    createdAt: '2025-10-10T14:00:00Z',
    tags: ['impermanent-loss', 'liquidity', 'lp', 'backtesting'],
    developer: { address: '0xCc3456Dd7890Ee0123Ff4567Aa8901Bb3456CcDd', name: 'ilwatch', agentCount: 1 },
  },
  {
    agentId: 'agent-mkt-034',
    name: 'FlashLoanDetector',
    description: 'Detects flash loan attacks and suspicious atomic transaction patterns.',
    longDescription:
      'FlashLoanDetector monitors mempool and confirmed transactions for flash loan usage patterns indicative of price manipulation, oracle exploitation, or governance attacks. It provides real-time alerts with full attack path visualization and affected protocol identification.',
    specialization: 'defi',
    tools: ['tx-decoder', 'flash-loan-tracker', 'attack-visualizer'],
    pricing: { perCall: 12, subscription: 180 },
    rating: 4.5,
    reviewCount: 38,
    totalCalls: 890,
    successRate: 94,
    avgResponseTime: 600,
    featured: false,
    verified: true,
    createdAt: '2025-11-05T08:45:00Z',
    tags: ['flash-loans', 'attacks', 'detection', 'defi-security'],
    developer: { address: '0xDd4567Ee8901Ff0123Aa5678Bb9012Cc4567DdEe', name: 'flashguard.xyz', agentCount: 2 },
  },
  {
    agentId: 'agent-mkt-035',
    name: 'YieldCompounder',
    description: 'Auto-compounds yields across vaults and staking protocols for maximum APY.',
    longDescription:
      'YieldCompounder calculates optimal compounding frequency based on gas costs and reward rates. It monitors Yearn, Beefy, Convex, and Pendle vaults, recommends the best auto-compounding strategies, and alerts when manual harvesting would be more profitable than gas spent.',
    specialization: 'defi',
    tools: ['vault-monitor', 'compound-calculator', 'harvest-optimizer'],
    pricing: { perCall: 5, subscription: 80 },
    rating: 4.3,
    reviewCount: 61,
    totalCalls: 4250,
    successRate: 96,
    avgResponseTime: 350,
    featured: false,
    verified: true,
    createdAt: '2025-12-01T10:20:00Z',
    tags: ['yield', 'compounding', 'vaults', 'auto-harvest'],
    developer: { address: '0xEe5678Ff9012Aa0123Bb6789Cc0123Dd5678EeFf', name: 'compoundoor', agentCount: 1 },
  },

  // ── Market Analysis (expanded) ────────────────────────
  {
    agentId: 'agent-mkt-036',
    name: 'CorrelationScanner',
    description: 'Maps price correlations between tokens, equities, and macro assets.',
    longDescription:
      'CorrelationScanner computes rolling correlation matrices between any combination of crypto tokens, stock indices, commodities, and bond yields. It detects regime changes when historically correlated assets decouple, and surfaces diversification opportunities.',
    specialization: 'market',
    tools: ['correlation-engine', 'multi-asset-fetcher', 'regime-detector'],
    pricing: { perCall: 10, subscription: 160 },
    rating: 4.3,
    reviewCount: 44,
    totalCalls: 1580,
    successRate: 95,
    avgResponseTime: 1200,
    featured: false,
    verified: true,
    createdAt: '2025-10-25T07:30:00Z',
    tags: ['correlation', 'macro', 'diversification', 'analytics'],
    developer: { address: '0xFf6789Aa0123Bb1234Cc7890Dd0123Ee6789FfAa', name: 'quantflow', agentCount: 4 },
  },
  {
    agentId: 'agent-mkt-037',
    name: 'FundingRateTracker',
    description: 'Monitors perpetual futures funding rates across all major exchanges.',
    longDescription:
      'FundingRateTracker aggregates funding rates from Binance, Bybit, dYdX, GMX, and Hyperliquid. It identifies extreme funding rate divergences that signal crowded trades, and calculates annualized carry trade returns from funding rate arbitrage.',
    specialization: 'market',
    tools: ['funding-aggregator', 'carry-calculator', 'divergence-alert'],
    pricing: { perCall: 7, subscription: 110 },
    rating: 4.5,
    reviewCount: 82,
    totalCalls: 5230,
    successRate: 98,
    avgResponseTime: 300,
    featured: false,
    verified: true,
    createdAt: '2025-09-08T15:00:00Z',
    tags: ['funding-rate', 'perpetuals', 'carry-trade', 'derivatives'],
    developer: { address: '0xAa7890Bb0123Cc2345Dd8901Ee0123Ff7890AaBb', name: 'perpmetrics', agentCount: 2 },
  },
  {
    agentId: 'agent-mkt-038',
    name: 'OpenInterestAnalyzer',
    description: 'Tracks open interest changes to identify leveraged position buildup.',
    longDescription:
      'OpenInterestAnalyzer monitors aggregate and per-exchange open interest for 200+ perpetual futures pairs. It detects rapid OI increases that suggest leveraged position accumulation, estimates liquidation clusters, and provides heatmaps of likely cascade zones.',
    specialization: 'market',
    tools: ['oi-tracker', 'liquidation-mapper', 'leverage-estimator'],
    pricing: { perCall: 9, subscription: 140 },
    rating: 4.4,
    reviewCount: 57,
    totalCalls: 2870,
    successRate: 93,
    avgResponseTime: 800,
    featured: false,
    verified: true,
    createdAt: '2025-11-15T12:00:00Z',
    tags: ['open-interest', 'leverage', 'derivatives', 'liquidations'],
    developer: { address: '0xBb8901Cc1234Dd3456Ee9012Ff1234Aa8901BbCc', name: 'perpmetrics', agentCount: 2 },
  },
  {
    agentId: 'agent-mkt-039',
    name: 'LiquidationTracker',
    description: 'Real-time liquidation feed with volume analysis and cascade prediction.',
    longDescription:
      'LiquidationTracker streams real-time liquidation events from CEX and on-chain perpetual protocols. It aggregates liquidation volumes by timeframe, identifies cascade patterns where liquidations trigger further liquidations, and provides early-warning alerts for large cluster zones.',
    specialization: 'market',
    tools: ['liquidation-feed', 'cascade-predictor', 'volume-aggregator'],
    pricing: { perCall: 8, subscription: 130 },
    rating: 4.6,
    reviewCount: 91,
    totalCalls: 6740,
    successRate: 96,
    avgResponseTime: 250,
    featured: true,
    verified: true,
    createdAt: '2025-08-28T06:00:00Z',
    tags: ['liquidations', 'perpetuals', 'cascade', 'real-time'],
    developer: { address: '0xCc9012Dd2345Ee4567Ff0123Aa2345Bb9012CcDd', name: 'liqwatch.io', agentCount: 3 },
  },

  // ── Security (expanded) ───────────────────────────────
  {
    agentId: 'agent-mkt-040',
    name: 'RugPullDetector',
    description: 'Scores new tokens for rug-pull risk using 30+ on-chain heuristics.',
    longDescription:
      'RugPullDetector analyzes token contracts for hidden mint functions, ownership centralization, locked vs unlocked liquidity, honeypot mechanics, and suspicious deployer history. It produces a composite risk score from 0-100 with detailed breakdown of each risk factor.',
    specialization: 'security',
    tools: ['contract-scanner', 'deployer-profiler', 'risk-scorer'],
    pricing: { perCall: 5, subscription: null },
    rating: 4.7,
    reviewCount: 143,
    totalCalls: 12800,
    successRate: 97,
    avgResponseTime: 400,
    featured: true,
    verified: true,
    createdAt: '2025-07-20T08:00:00Z',
    tags: ['rug-pull', 'scam', 'token-safety', 'detection'],
    developer: { address: '0xDd0123Ee3456Ff5678Aa1234Bb3456Cc0123DdEe', name: 'shieldwall.eth', agentCount: 2 },
  },
  {
    agentId: 'agent-mkt-041',
    name: 'HoneypotChecker',
    description: 'Simulates buy/sell transactions to detect honeypot token traps.',
    longDescription:
      'HoneypotChecker uses trace-call simulation to test whether a token can actually be sold after purchase. It checks for hidden transfer fees, max-transaction limits, blacklist functions, and anti-whale mechanisms that could trap buyers. Results include detailed fee breakdown and sell simulation outcomes.',
    specialization: 'security',
    tools: ['tx-simulator', 'fee-analyzer', 'blacklist-checker'],
    pricing: { perCall: 3, subscription: null },
    rating: 4.6,
    reviewCount: 167,
    totalCalls: 18500,
    successRate: 99,
    avgResponseTime: 300,
    featured: false,
    verified: true,
    createdAt: '2025-08-05T10:30:00Z',
    tags: ['honeypot', 'scam', 'simulation', 'token-safety'],
    developer: { address: '0xEe1234Ff4567Aa6789Bb2345Cc4567Dd1234EeFf', name: 'tokensafe.dev', agentCount: 2 },
  },
  {
    agentId: 'agent-mkt-042',
    name: 'WalletDrainerAlert',
    description: 'Monitors connected wallets for suspicious approval and drain attempts.',
    longDescription:
      'WalletDrainerAlert continuously scans your approved token allowances and monitors for known drainer contract patterns. It sends instant push alerts when a malicious approval is detected, provides one-click revoke suggestions, and maintains a real-time database of 50,000+ flagged drainer addresses.',
    specialization: 'security',
    tools: ['approval-monitor', 'drainer-db', 'revoke-helper'],
    pricing: { perCall: 2, subscription: 50 },
    rating: 4.8,
    reviewCount: 203,
    totalCalls: 24300,
    successRate: 99.5,
    avgResponseTime: 200,
    featured: false,
    verified: true,
    createdAt: '2025-07-10T05:00:00Z',
    tags: ['drainer', 'wallet-security', 'approvals', 'alerts'],
    developer: { address: '0xFf2345Aa5678Bb7890Cc3456Dd5678Ee2345FfAa', name: 'fortressec', agentCount: 3 },
  },
  {
    agentId: 'agent-mkt-043',
    name: 'GovAttackMonitor',
    description: 'Detects governance attacks including flash-loan voting and proposal hijacks.',
    longDescription:
      'GovAttackMonitor watches DAO governance systems for attack patterns: flash-loan powered vote manipulation, sudden delegation spikes before contentious proposals, malicious proposal injection, and timelock bypasses. It covers Compound Governor, OpenZeppelin Governor, and custom implementations.',
    specialization: 'security',
    tools: ['gov-watcher', 'delegation-tracker', 'attack-classifier'],
    pricing: { perCall: 15, subscription: 200 },
    rating: 4.3,
    reviewCount: 29,
    totalCalls: 520,
    successRate: 94,
    avgResponseTime: 900,
    featured: false,
    verified: true,
    createdAt: '2025-12-15T16:00:00Z',
    tags: ['governance', 'attacks', 'dao-security', 'voting'],
    developer: { address: '0xAa3456Bb6789Cc8901Dd4567Ee6789Ff3456AaBb', name: 'govguard', agentCount: 1 },
  },

  // ── Research (expanded) ───────────────────────────────
  {
    agentId: 'agent-mkt-044',
    name: 'WhitepaperAnalyzer',
    description: 'Reads and critiques project whitepapers for technical soundness and red flags.',
    longDescription:
      'WhitepaperAnalyzer ingests PDF or markdown whitepapers and produces structured reviews covering technical feasibility, novelty of approach, tokenomics sustainability, team claims verification, and comparison with similar existing projects. It flags common red flags like plagiarized content and unrealistic performance claims.',
    specialization: 'research',
    tools: ['pdf-parser', 'plagiarism-checker', 'tech-evaluator'],
    pricing: { perCall: 20, subscription: null },
    rating: 4.5,
    reviewCount: 48,
    totalCalls: 870,
    successRate: 96,
    avgResponseTime: 3500,
    featured: false,
    verified: true,
    createdAt: '2025-10-01T09:00:00Z',
    tags: ['whitepaper', 'research', 'analysis', 'due-diligence'],
    developer: { address: '0xBb4567Cc7890Dd9012Ee5678Ff7890Aa4567BbCc', name: 'labyrinth.research', agentCount: 3 },
  },
  {
    agentId: 'agent-mkt-045',
    name: 'TeamVerifier',
    description: 'Background checks project teams via LinkedIn, GitHub, and on-chain history.',
    longDescription:
      'TeamVerifier cross-references team member claims against LinkedIn profiles, GitHub contribution history, prior project involvement, and on-chain wallet activity. It flags anonymous teams, fake credentials, and connections to previously failed or scam projects.',
    specialization: 'research',
    tools: ['linkedin-verifier', 'github-scanner', 'wallet-linker'],
    pricing: { perCall: 25, subscription: null },
    rating: 4.4,
    reviewCount: 36,
    totalCalls: 640,
    successRate: 92,
    avgResponseTime: 4000,
    featured: false,
    verified: true,
    createdAt: '2025-11-20T13:00:00Z',
    tags: ['team', 'verification', 'background-check', 'due-diligence'],
    developer: { address: '0xCc5678Dd8901Ee0123Ff6789Aa8901Bb5678CcDd', name: 'veridao', agentCount: 2 },
  },
  {
    agentId: 'agent-mkt-046',
    name: 'EcosystemMapper',
    description: 'Maps protocol ecosystems showing integrations, dependencies, and money flow.',
    longDescription:
      'EcosystemMapper produces interactive dependency graphs for any blockchain ecosystem. It visualizes protocol integrations, shared oracle dependencies, liquidity flows between protocols, and governance token holder overlap. Useful for understanding systemic risk and finding undervalued ecosystem plays.',
    specialization: 'research',
    tools: ['graph-builder', 'integration-scanner', 'flow-analyzer'],
    pricing: { perCall: 15, subscription: 220 },
    rating: 4.6,
    reviewCount: 42,
    totalCalls: 780,
    successRate: 95,
    avgResponseTime: 2800,
    featured: false,
    verified: true,
    createdAt: '2025-09-18T07:30:00Z',
    tags: ['ecosystem', 'mapping', 'dependencies', 'integrations'],
    developer: { address: '0xDd6789Ee9012Ff1234Aa7890Bb9012Cc6789DdEe', name: 'graphlabs.xyz', agentCount: 2 },
  },
  {
    agentId: 'agent-mkt-047',
    name: 'CompetitorTracker',
    description: 'Monitors competitor protocols for feature launches, TVL changes, and narrative shifts.',
    longDescription:
      'CompetitorTracker lets you define a watchlist of competing protocols and tracks their GitHub commits, governance proposals, TVL changes, social media activity, and partnership announcements. It produces weekly competitive intelligence briefs with trend analysis.',
    specialization: 'research',
    tools: ['protocol-monitor', 'tvl-tracker', 'narrative-analyzer'],
    pricing: { perCall: 12, subscription: 180 },
    rating: 4.2,
    reviewCount: 31,
    totalCalls: 560,
    successRate: 93,
    avgResponseTime: 1800,
    featured: false,
    verified: true,
    createdAt: '2025-12-08T11:15:00Z',
    tags: ['competitor', 'intelligence', 'tvl', 'monitoring'],
    developer: { address: '0xEe7890Ff0123Aa2345Bb8901Cc0123Dd7890EeFf', name: 'intelnode', agentCount: 1 },
  },

  // ── NFT (expanded) ────────────────────────────────────
  {
    agentId: 'agent-mkt-048',
    name: 'RaritySniper',
    description: 'Calculates real-time rarity scores and finds underpriced rare NFTs.',
    longDescription:
      'RaritySniper computes trait rarity rankings using statistical methods (information-content scoring, not simple percentage). It monitors new listings and alerts when rare items are listed below their rarity-adjusted fair value, giving snipers a data edge.',
    specialization: 'nft',
    tools: ['rarity-engine', 'listing-monitor', 'fair-value-model'],
    pricing: { perCall: 8, subscription: 120 },
    rating: 4.3,
    reviewCount: 67,
    totalCalls: 3450,
    successRate: 91,
    avgResponseTime: 500,
    featured: false,
    verified: true,
    createdAt: '2025-09-25T18:00:00Z',
    tags: ['nft', 'rarity', 'sniping', 'traits'],
    developer: { address: '0xFf8901Aa1234Bb3456Cc9012Dd1234Ee8901FfAa', name: 'nftgrinder', agentCount: 1 },
  },
  {
    agentId: 'agent-mkt-049',
    name: 'WashTradeDetector',
    description: 'Identifies wash trading activity in NFT collections to reveal true volume.',
    longDescription:
      'WashTradeDetector analyzes NFT transaction graphs to identify circular trading patterns, self-trades through intermediary wallets, and coordinated volume inflation. It produces a "genuine volume" metric that strips out detected wash trades, helping users avoid collections with artificially inflated activity.',
    specialization: 'nft',
    tools: ['graph-analyzer', 'wash-classifier', 'volume-corrector'],
    pricing: { perCall: 10, subscription: null },
    rating: 4.4,
    reviewCount: 39,
    totalCalls: 1120,
    successRate: 93,
    avgResponseTime: 1500,
    featured: false,
    verified: true,
    createdAt: '2025-10-20T14:30:00Z',
    tags: ['nft', 'wash-trading', 'volume', 'fraud-detection'],
    developer: { address: '0xAa9012Bb2345Cc4567Dd0123Ee2345Ff9012AaBb', name: 'nftguard', agentCount: 2 },
  },
  {
    agentId: 'agent-mkt-050',
    name: 'CollectionAnalyzer',
    description: 'Deep analytics for NFT collections including holder distribution and momentum.',
    longDescription:
      'CollectionAnalyzer provides comprehensive metrics for any NFT collection: holder concentration (Gini coefficient), diamond-hand ratio, listing-to-floor ratio, unique buyer trends, and social sentiment. It ranks collections by momentum score and flags potential pumps or dumps.',
    specialization: 'nft',
    tools: ['holder-analyzer', 'momentum-scorer', 'collection-ranker'],
    pricing: { perCall: 7, subscription: null },
    rating: 4.1,
    reviewCount: 44,
    totalCalls: 1680,
    successRate: 92,
    avgResponseTime: 1100,
    featured: false,
    verified: false,
    createdAt: '2025-11-30T20:00:00Z',
    tags: ['nft', 'analytics', 'holders', 'momentum'],
    developer: { address: '0xBb0123Cc3456Dd5678Ee1234Ff3456Aa0123BbCc', name: 'nftmetrics.xyz', agentCount: 1 },
  },

  // ── News (expanded) ───────────────────────────────────
  {
    agentId: 'agent-mkt-051',
    name: 'RegulatoryAlert',
    description: 'Instant alerts on regulatory actions affecting crypto markets worldwide.',
    longDescription:
      'RegulatoryAlert monitors SEC filings, CFTC orders, EU parliament votes, and regulatory body announcements from 40+ countries. It sends push notifications within minutes of publication, categorized by impact severity and affected asset classes (DeFi, stablecoins, exchanges, mining).',
    specialization: 'news',
    tools: ['filing-monitor', 'impact-classifier', 'push-notifier'],
    pricing: { perCall: 5, subscription: 80 },
    rating: 4.5,
    reviewCount: 72,
    totalCalls: 4100,
    successRate: 98,
    avgResponseTime: 300,
    featured: false,
    verified: true,
    createdAt: '2025-08-12T06:00:00Z',
    tags: ['regulation', 'alerts', 'sec', 'compliance'],
    developer: { address: '0xCc1234Dd4567Ee6789Ff2345Aa4567Bb1234CcDd', name: 'compliancenode', agentCount: 1 },
  },
  {
    agentId: 'agent-mkt-052',
    name: 'MacroEventTracker',
    description: 'Tracks macro events (FOMC, CPI, jobs) and their crypto market impact.',
    longDescription:
      'MacroEventTracker maintains a calendar of major macroeconomic events and correlates them with historical crypto market reactions. It provides pre-event positioning analysis, real-time deviation tracking when data is released, and post-event impact summaries.',
    specialization: 'news',
    tools: ['event-calendar', 'deviation-tracker', 'impact-analyzer'],
    pricing: { perCall: 6, subscription: 90 },
    rating: 4.4,
    reviewCount: 58,
    totalCalls: 2340,
    successRate: 96,
    avgResponseTime: 400,
    featured: false,
    verified: true,
    createdAt: '2025-09-30T08:00:00Z',
    tags: ['macro', 'fomc', 'cpi', 'economic-events'],
    developer: { address: '0xDd2345Ee5678Ff7890Aa3456Bb5678Cc2345DdEe', name: 'macrolens', agentCount: 2 },
  },
  {
    agentId: 'agent-mkt-053',
    name: 'EarningsCalendar',
    description: 'Tracks crypto company earnings, token unlock schedules, and protocol milestones.',
    longDescription:
      'EarningsCalendar aggregates quarterly earnings from publicly-traded crypto companies (Coinbase, MicroStrategy, Marathon), major token unlock events, protocol upgrade dates, and airdrop snapshots into a unified calendar. Each event includes historical price reaction data.',
    specialization: 'news',
    tools: ['calendar-aggregator', 'unlock-tracker', 'price-reaction-db'],
    pricing: { perCall: 4, subscription: 60 },
    rating: 4.2,
    reviewCount: 35,
    totalCalls: 1450,
    successRate: 97,
    avgResponseTime: 350,
    featured: false,
    verified: true,
    createdAt: '2025-10-15T11:00:00Z',
    tags: ['earnings', 'calendar', 'unlocks', 'milestones'],
    developer: { address: '0xEe3456Ff6789Aa8901Bb4567Cc6789Dd3456EeFf', name: 'eventnode.io', agentCount: 1 },
  },

  // ── Social / KOL ──────────────────────────────────────
  {
    agentId: 'agent-mkt-054',
    name: 'InfluencerTracker',
    description: 'Tracks crypto influencer trading activity and call accuracy over time.',
    longDescription:
      'InfluencerTracker links known influencer wallets to their public calls, calculating hit rates, average returns, and timing accuracy. It ranks KOLs by actual on-chain performance rather than follower count, and alerts when tracked influencers make new positions.',
    specialization: 'social',
    tools: ['kol-mapper', 'call-tracker', 'performance-ranker'],
    pricing: { perCall: 10, subscription: 150 },
    rating: 4.5,
    reviewCount: 89,
    totalCalls: 4780,
    successRate: 94,
    avgResponseTime: 700,
    featured: true,
    verified: true,
    createdAt: '2025-08-20T10:00:00Z',
    tags: ['influencer', 'kol', 'tracking', 'performance'],
    developer: { address: '0xFf4567Aa7890Bb9012Cc5678Dd7890Ee4567FfAa', name: 'socialedge', agentCount: 3 },
  },
  {
    agentId: 'agent-mkt-055',
    name: 'ShillDetector',
    description: 'Identifies paid promotions and coordinated shilling campaigns.',
    longDescription:
      'ShillDetector analyzes social media activity patterns to identify coordinated promotion campaigns. It detects bot networks, paid shill accounts, and astroturfed engagement by analyzing posting timing, account age clusters, and content similarity patterns across Twitter, Telegram, and Discord.',
    specialization: 'social',
    tools: ['bot-detector', 'coordination-analyzer', 'campaign-identifier'],
    pricing: { perCall: 6, subscription: null },
    rating: 4.3,
    reviewCount: 54,
    totalCalls: 2130,
    successRate: 91,
    avgResponseTime: 1200,
    featured: false,
    verified: true,
    createdAt: '2025-10-05T15:30:00Z',
    tags: ['shill', 'bot-detection', 'social', 'manipulation'],
    developer: { address: '0xAa5678Bb8901Cc0123Dd6789Ee8901Ff5678AaBb', name: 'truthlens', agentCount: 2 },
  },
  {
    agentId: 'agent-mkt-056',
    name: 'CommunitySentiment',
    description: 'Measures community health and sentiment across Telegram, Discord, and forums.',
    longDescription:
      'CommunitySentiment provides deep community analytics beyond simple sentiment scores. It tracks active member growth, message quality, developer engagement in community channels, moderator responsiveness, and FUD/hype cycles. Produces weekly community health reports.',
    specialization: 'social',
    tools: ['community-analyzer', 'engagement-scorer', 'health-reporter'],
    pricing: { perCall: 8, subscription: 120 },
    rating: 4.1,
    reviewCount: 37,
    totalCalls: 1340,
    successRate: 93,
    avgResponseTime: 1500,
    featured: false,
    verified: true,
    createdAt: '2025-11-08T09:00:00Z',
    tags: ['community', 'sentiment', 'telegram', 'discord'],
    developer: { address: '0xBb6789Cc9012Dd1234Ee7890Ff9012Aa6789BbCc', name: 'pulsemetrics', agentCount: 2 },
  },
  {
    agentId: 'agent-mkt-057',
    name: 'ViralPredictor',
    description: 'Predicts which crypto narratives and memes will go viral based on early signals.',
    longDescription:
      'ViralPredictor uses early engagement velocity, network propagation patterns, and historical narrative cycle data to predict which emerging topics will achieve viral status. It surfaces nascent narratives 12-48 hours before mainstream crypto Twitter picks them up.',
    specialization: 'social',
    tools: ['velocity-tracker', 'propagation-model', 'narrative-classifier'],
    pricing: { perCall: 12, subscription: 200 },
    rating: 4.0,
    reviewCount: 26,
    totalCalls: 680,
    successRate: 88,
    avgResponseTime: 1800,
    featured: false,
    verified: false,
    createdAt: '2025-12-18T14:00:00Z',
    tags: ['viral', 'narratives', 'prediction', 'memes'],
    developer: { address: '0xCc7890Dd0123Ee2345Ff8901Aa0123Bb7890CcDd', name: 'viralnode', agentCount: 2 },
  },
  {
    agentId: 'agent-mkt-058',
    name: 'SocialEngagementScorer',
    description: 'Scores project social media engagement quality to filter real vs fake growth.',
    longDescription:
      'SocialEngagementScorer evaluates the quality of social engagement for any crypto project. It distinguishes genuine community interaction from bot-driven metrics by analyzing reply depth, conversation quality, follower-to-engagement ratios, and geographic distribution of activity.',
    specialization: 'social',
    tools: ['engagement-analyzer', 'quality-scorer', 'bot-filter'],
    pricing: { perCall: 5, subscription: null },
    rating: 4.2,
    reviewCount: 43,
    totalCalls: 1890,
    successRate: 94,
    avgResponseTime: 900,
    featured: false,
    verified: true,
    createdAt: '2025-10-28T17:00:00Z',
    tags: ['engagement', 'social-metrics', 'quality', 'scoring'],
    developer: { address: '0xDd8901Ee1234Ff3456Aa9012Bb1234Cc8901DdEe', name: 'socialedge', agentCount: 3 },
  },

  // ── Infrastructure ────────────────────────────────────
  {
    agentId: 'agent-mkt-059',
    name: 'RPCHealthMonitor',
    description: 'Monitors RPC endpoint latency, uptime, and data consistency across providers.',
    longDescription:
      'RPCHealthMonitor continuously pings RPC endpoints from Alchemy, Infura, QuickNode, Ankr, and public RPCs across 20+ chains. It measures response latency, block height lag, data consistency, and error rates. Automatically recommends failover endpoints when primary providers degrade.',
    specialization: 'infrastructure',
    tools: ['rpc-pinger', 'consistency-checker', 'failover-engine'],
    pricing: { perCall: 2, subscription: 40 },
    rating: 4.6,
    reviewCount: 52,
    totalCalls: 48200,
    successRate: 99.5,
    avgResponseTime: 150,
    featured: false,
    verified: true,
    createdAt: '2025-08-25T04:00:00Z',
    tags: ['rpc', 'infrastructure', 'monitoring', 'uptime'],
    developer: { address: '0xEe9012Ff2345Aa4567Bb0123Cc2345Dd9012EeFf', name: 'nodeops.xyz', agentCount: 4 },
  },
  {
    agentId: 'agent-mkt-060',
    name: 'GasOptimizer',
    description: 'Analyzes contract bytecode and suggests gas-saving optimizations.',
    longDescription:
      'GasOptimizer performs deep analysis of deployed or undeployed Solidity contracts to identify gas optimization opportunities. It suggests storage packing, calldata optimization, loop unrolling, and Yul assembly replacements. Provides estimated gas savings per suggestion with before/after comparisons.',
    specialization: 'infrastructure',
    tools: ['bytecode-analyzer', 'optimization-engine', 'gas-estimator'],
    pricing: { perCall: 15, subscription: null },
    rating: 4.4,
    reviewCount: 38,
    totalCalls: 920,
    successRate: 96,
    avgResponseTime: 2500,
    featured: false,
    verified: true,
    createdAt: '2025-10-12T12:30:00Z',
    tags: ['gas', 'optimization', 'solidity', 'bytecode'],
    developer: { address: '0xFf0123Aa3456Bb5678Cc1234Dd3456Ee0123FfAa', name: 'gasworks.eth', agentCount: 1 },
  },
  {
    agentId: 'agent-mkt-061',
    name: 'MEVTracker',
    description: 'Tracks MEV extraction across Ethereum and L2s with builder and searcher analytics.',
    longDescription:
      'MEVTracker provides comprehensive MEV analytics: total extracted value per block, top searcher profitability, builder market share, sandwich attack volume, and arbitrage opportunity sizing. It helps researchers and protocol teams understand the MEV landscape affecting their users.',
    specialization: 'infrastructure',
    tools: ['mev-indexer', 'builder-analyzer', 'searcher-profiler'],
    pricing: { perCall: 10, subscription: 160 },
    rating: 4.5,
    reviewCount: 45,
    totalCalls: 1670,
    successRate: 95,
    avgResponseTime: 1100,
    featured: false,
    verified: true,
    createdAt: '2025-09-10T07:00:00Z',
    tags: ['mev', 'builders', 'searchers', 'analytics'],
    developer: { address: '0xAa1234Cc4567Dd6789Ee2345Ff4567Aa1234BbCc', name: 'darkforest.dev', agentCount: 2 },
  },
  {
    agentId: 'agent-mkt-062',
    name: 'BlockAnalyzer',
    description: 'Deep analysis of block contents including transaction ordering and MEV impact.',
    longDescription:
      'BlockAnalyzer breaks down any Ethereum or L2 block into human-readable summaries. It categorizes transactions by type (swap, transfer, mint, governance), identifies MEV bundles, calculates effective gas prices, and visualizes transaction ordering to reveal builder strategies.',
    specialization: 'infrastructure',
    tools: ['block-parser', 'tx-categorizer', 'bundle-detector'],
    pricing: { perCall: 5, subscription: null },
    rating: 4.2,
    reviewCount: 28,
    totalCalls: 780,
    successRate: 97,
    avgResponseTime: 800,
    featured: false,
    verified: true,
    createdAt: '2025-11-22T15:00:00Z',
    tags: ['blocks', 'analysis', 'transactions', 'ordering'],
    developer: { address: '0xBb2345Dd5678Ee7890Ff3456Aa5678Bb2345CcDd', name: 'blockscope.io', agentCount: 1 },
  },
  {
    agentId: 'agent-mkt-063',
    name: 'ValidatorMonitor',
    description: 'Tracks validator performance, slashing events, and staking economics.',
    longDescription:
      'ValidatorMonitor provides real-time analytics for Ethereum validators and other PoS chains. It tracks attestation effectiveness, proposal success rates, slashing events across the network, and calculates expected staking returns accounting for MEV tips and timing games.',
    specialization: 'infrastructure',
    tools: ['validator-tracker', 'slashing-monitor', 'staking-calculator'],
    pricing: { perCall: 4, subscription: 70 },
    rating: 4.3,
    reviewCount: 33,
    totalCalls: 2340,
    successRate: 98,
    avgResponseTime: 600,
    featured: false,
    verified: true,
    createdAt: '2025-10-08T06:30:00Z',
    tags: ['validators', 'staking', 'slashing', 'ethereum'],
    developer: { address: '0xCc3456Ee6789Ff8901Aa4567Bb6789Cc3456DdEe', name: 'stakehouse.eth', agentCount: 2 },
  },

  // ── Data Analytics ────────────────────────────────────
  {
    agentId: 'agent-mkt-064',
    name: 'OnChainAnalytics',
    description: 'Comprehensive on-chain metrics for any EVM token with Dune-like queries.',
    longDescription:
      'OnChainAnalytics provides Dune Analytics-style querying through natural language. Ask questions like "show me daily active addresses for PEPE over the last 30 days" and get formatted charts and data tables. Covers holder distribution, transfer volumes, DEX activity, and smart money flows.',
    specialization: 'data-analytics',
    tools: ['query-engine', 'chart-renderer', 'data-fetcher'],
    pricing: { perCall: 8, subscription: 130 },
    rating: 4.7,
    reviewCount: 96,
    totalCalls: 5670,
    successRate: 95,
    avgResponseTime: 1800,
    featured: true,
    verified: true,
    createdAt: '2025-07-28T09:00:00Z',
    tags: ['on-chain', 'analytics', 'metrics', 'dune'],
    developer: { address: '0xDd4567Ff7890Aa9012Bb5678Cc7890Dd4567EeFf', name: 'dataforge.eth', agentCount: 5 },
  },
  {
    agentId: 'agent-mkt-065',
    name: 'TVLTracker',
    description: 'Real-time TVL tracking across protocols with inflow/outflow analysis.',
    longDescription:
      'TVLTracker monitors total value locked across 500+ DeFi protocols on 30+ chains. It provides real-time TVL changes, daily inflow/outflow breakdowns, TVL composition by asset type, and historical comparisons. Alerts on significant TVL drops that may indicate protocol distress.',
    specialization: 'data-analytics',
    tools: ['tvl-indexer', 'flow-analyzer', 'protocol-ranker'],
    pricing: { perCall: 5, subscription: 80 },
    rating: 4.5,
    reviewCount: 71,
    totalCalls: 3890,
    successRate: 97,
    avgResponseTime: 500,
    featured: false,
    verified: true,
    createdAt: '2025-08-30T11:00:00Z',
    tags: ['tvl', 'defi', 'inflows', 'analytics'],
    developer: { address: '0xEe5678Aa8901Bb0123Cc6789Dd8901Ee5678FfAa', name: 'dataforge.eth', agentCount: 5 },
  },
  {
    agentId: 'agent-mkt-066',
    name: 'TokenFlowMapper',
    description: 'Visualizes token movement between wallets, exchanges, and protocols.',
    longDescription:
      'TokenFlowMapper creates Sankey diagrams and flow visualizations showing where tokens move after major events (unlocks, airdrops, liquidations). It traces token paths through mixers, bridges, and intermediary wallets, helping users understand the full lifecycle of token distribution.',
    specialization: 'data-analytics',
    tools: ['flow-tracer', 'sankey-renderer', 'path-analyzer'],
    pricing: { perCall: 12, subscription: null },
    rating: 4.3,
    reviewCount: 34,
    totalCalls: 890,
    successRate: 94,
    avgResponseTime: 2200,
    featured: false,
    verified: true,
    createdAt: '2025-11-01T13:30:00Z',
    tags: ['token-flow', 'visualization', 'tracing', 'analytics'],
    developer: { address: '0xFf6789Bb9012Cc1234Dd7890Ee9012Ff6789AaBb', name: 'flowvis.xyz', agentCount: 1 },
  },
  {
    agentId: 'agent-mkt-067',
    name: 'WhaleDecoder',
    description: 'Decodes complex whale transactions and explains their likely intent.',
    longDescription:
      'WhaleDecoder takes any transaction hash and produces a human-readable explanation of what happened, who was involved, and what the likely motivation was. It specializes in complex multi-step DeFi transactions, flash loans, and smart contract interactions that are hard to parse from raw data.',
    specialization: 'data-analytics',
    tools: ['tx-decoder', 'intent-classifier', 'entity-resolver'],
    pricing: { perCall: 7, subscription: null },
    rating: 4.4,
    reviewCount: 62,
    totalCalls: 2450,
    successRate: 92,
    avgResponseTime: 1000,
    featured: false,
    verified: true,
    createdAt: '2025-09-20T08:45:00Z',
    tags: ['whales', 'transactions', 'decoding', 'analytics'],
    developer: { address: '0xAa7890Cc0123Dd2345Ee8901Ff0123Aa7890BbCc', name: 'deepflow', agentCount: 3 },
  },
  {
    agentId: 'agent-mkt-068',
    name: 'CrossChainTracker',
    description: 'Tracks asset movements across bridges and chains with unified view.',
    longDescription:
      'CrossChainTracker provides a unified view of cross-chain asset flows. It monitors all major bridges, tracks bridged asset peg stability, identifies chains gaining or losing capital, and alerts on unusually large cross-chain transfers that may signal smart money rotation.',
    specialization: 'data-analytics',
    tools: ['bridge-monitor', 'cross-chain-aggregator', 'rotation-detector'],
    pricing: { perCall: 6, subscription: 100 },
    rating: 4.3,
    reviewCount: 47,
    totalCalls: 1780,
    successRate: 95,
    avgResponseTime: 900,
    featured: false,
    verified: true,
    createdAt: '2025-10-30T16:00:00Z',
    tags: ['cross-chain', 'bridges', 'flows', 'multi-chain'],
    developer: { address: '0xBb8901Dd1234Ee3456Ff9012Aa1234Bb8901CcDd', name: 'bridgelabs.eth', agentCount: 1 },
  },

  // ── Legal / Compliance ────────────────────────────────
  {
    agentId: 'agent-mkt-069',
    name: 'SanctionsChecker',
    description: 'Screens wallet addresses against OFAC, EU, and global sanctions lists.',
    longDescription:
      'SanctionsChecker provides instant screening of any wallet address against OFAC SDN, EU consolidated sanctions, UK HMT, and 15+ other international sanctions lists. It also checks for indirect exposure through known mixer and darknet market addresses, and provides compliance-ready audit reports.',
    specialization: 'legal',
    tools: ['sanctions-db', 'exposure-analyzer', 'compliance-reporter'],
    pricing: { perCall: 3, subscription: 50 },
    rating: 4.7,
    reviewCount: 84,
    totalCalls: 9800,
    successRate: 99.8,
    avgResponseTime: 200,
    featured: false,
    verified: true,
    createdAt: '2025-07-25T06:00:00Z',
    tags: ['sanctions', 'ofac', 'compliance', 'screening'],
    developer: { address: '0xCc9012Ee2345Ff4567Aa0123Bb2345Cc9012DdEe', name: 'compliancenode', agentCount: 1 },
  },
  {
    agentId: 'agent-mkt-070',
    name: 'TravelRuleValidator',
    description: 'Validates travel rule compliance for crypto transfers above regulatory thresholds.',
    longDescription:
      'TravelRuleValidator helps VASPs and institutions comply with FATF travel rule requirements. It identifies transfers that exceed jurisdictional thresholds, validates counterparty VASP information, and generates required data packages for originator and beneficiary information exchange.',
    specialization: 'legal',
    tools: ['threshold-checker', 'vasp-validator', 'data-packager'],
    pricing: { perCall: 8, subscription: 120 },
    rating: 4.2,
    reviewCount: 21,
    totalCalls: 340,
    successRate: 98,
    avgResponseTime: 500,
    featured: false,
    verified: true,
    createdAt: '2025-12-22T10:00:00Z',
    tags: ['travel-rule', 'fatf', 'compliance', 'vasp'],
    developer: { address: '0xDd0123Ff3456Aa5678Bb1234Cc3456Dd0123EeFf', name: 'reglabs.io', agentCount: 2 },
  },
  {
    agentId: 'agent-mkt-071',
    name: 'CryptoTaxOptimizer',
    description: 'Optimizes tax liability through loss harvesting and lot selection strategies.',
    longDescription:
      'CryptoTaxOptimizer goes beyond basic tax reporting to actively suggest tax optimization strategies. It identifies tax-loss harvesting opportunities, recommends optimal cost-basis methods (FIFO, LIFO, specific identification), and models the tax impact of planned trades before execution.',
    specialization: 'legal',
    tools: ['harvest-finder', 'lot-optimizer', 'tax-modeler'],
    pricing: { perCall: 15, subscription: 200 },
    rating: 4.5,
    reviewCount: 56,
    totalCalls: 1240,
    successRate: 95,
    avgResponseTime: 1500,
    featured: false,
    verified: true,
    createdAt: '2025-09-05T14:00:00Z',
    tags: ['tax', 'optimization', 'loss-harvesting', 'legal'],
    developer: { address: '0xEe1234Aa4567Bb6789Cc2345Dd4567Ee1234FfAa', name: 'taxnodes', agentCount: 2 },
  },
  {
    agentId: 'agent-mkt-072',
    name: 'ComplianceScanner',
    description: 'Scans DeFi protocols for regulatory compliance risks across jurisdictions.',
    longDescription:
      'ComplianceScanner evaluates DeFi protocols against regulatory frameworks in the US, EU (MiCA), UK, Singapore, and Hong Kong. It assesses whether protocols might be classified as securities, money transmitters, or regulated financial services, and flags potential compliance gaps.',
    specialization: 'legal',
    tools: ['regulation-mapper', 'protocol-classifier', 'risk-assessor'],
    pricing: { perCall: 20, subscription: null },
    rating: 4.1,
    reviewCount: 18,
    totalCalls: 280,
    successRate: 93,
    avgResponseTime: 3000,
    featured: false,
    verified: false,
    createdAt: '2026-01-10T09:30:00Z',
    tags: ['compliance', 'regulation', 'mica', 'risk-assessment'],
    developer: { address: '0xFf2345Bb5678Cc7890Dd3456Ee5678Ff2345AaBb', name: 'reglabs.io', agentCount: 2 },
  },

  // ── Trading ───────────────────────────────────────────
  {
    agentId: 'agent-mkt-073',
    name: 'GridBotAssistant',
    description: 'Configures and optimizes grid trading strategies based on volatility analysis.',
    longDescription:
      'GridBotAssistant analyzes historical volatility, support/resistance levels, and current market conditions to recommend optimal grid trading parameters (range, grid count, investment amount). It backtests configurations against recent data and adjusts recommendations as market conditions change.',
    specialization: 'trading',
    tools: ['volatility-analyzer', 'grid-optimizer', 'backtest-engine'],
    pricing: { perCall: 10, subscription: 150 },
    rating: 4.3,
    reviewCount: 64,
    totalCalls: 2890,
    successRate: 92,
    avgResponseTime: 1200,
    featured: false,
    verified: true,
    createdAt: '2025-09-15T10:00:00Z',
    tags: ['grid-trading', 'bot', 'volatility', 'strategy'],
    developer: { address: '0xAa3456Cc6789Dd8901Ee4567Ff6789Aa3456BbCc', name: 'tradecraft.io', agentCount: 4 },
  },
  {
    agentId: 'agent-mkt-074',
    name: 'DCAOptimizer',
    description: 'Optimizes dollar-cost averaging schedules using volatility and trend signals.',
    longDescription:
      'DCAOptimizer enhances basic DCA strategies with market-aware timing. It analyzes volatility regimes, fear/greed indices, and technical momentum to suggest when to increase or decrease DCA amounts. Backtested against simple DCA to demonstrate alpha from smart-DCA approaches.',
    specialization: 'trading',
    tools: ['dca-engine', 'regime-detector', 'schedule-optimizer'],
    pricing: { perCall: 5, subscription: 80 },
    rating: 4.4,
    reviewCount: 73,
    totalCalls: 3560,
    successRate: 96,
    avgResponseTime: 600,
    featured: false,
    verified: true,
    createdAt: '2025-10-20T08:30:00Z',
    tags: ['dca', 'dollar-cost-averaging', 'strategy', 'optimization'],
    developer: { address: '0xBb4567Dd7890Ee9012Ff5678Aa7890Bb4567CcDd', name: 'tradecraft.io', agentCount: 4 },
  },
  {
    agentId: 'agent-mkt-075',
    name: 'ArbitrageFinder',
    description: 'Identifies cross-exchange and cross-chain arbitrage opportunities in real time.',
    longDescription:
      'ArbitrageFinder monitors price discrepancies across CEX, DEX, and cross-chain venues for 1000+ token pairs. It calculates net profit after fees, gas, bridge costs, and slippage, and ranks opportunities by risk-adjusted return. Supports spot arbitrage, triangular arbitrage, and cross-chain routes.',
    specialization: 'trading',
    tools: ['price-monitor', 'arb-calculator', 'route-optimizer'],
    pricing: { perCall: 15, subscription: 250 },
    rating: 4.1,
    reviewCount: 41,
    totalCalls: 1870,
    successRate: 90,
    avgResponseTime: 300,
    featured: false,
    verified: true,
    createdAt: '2025-11-10T06:00:00Z',
    tags: ['arbitrage', 'cross-exchange', 'trading', 'opportunities'],
    developer: { address: '0xCc5678Ee8901Ff0123Aa6789Bb8901Cc5678DdEe', name: 'arbnode.eth', agentCount: 1 },
  },
  {
    agentId: 'agent-mkt-076',
    name: 'PortfolioRebalancer',
    description: 'Recommends portfolio rebalancing trades to maintain target allocations.',
    longDescription:
      'PortfolioRebalancer monitors your actual portfolio weights against target allocations and recommends rebalancing trades when drift exceeds configurable thresholds. It accounts for tax implications, transaction costs, and slippage to determine the most efficient rebalancing path.',
    specialization: 'trading',
    tools: ['drift-calculator', 'rebalance-optimizer', 'tax-impact-modeler'],
    pricing: { perCall: 8, subscription: 120 },
    rating: 4.5,
    reviewCount: 58,
    totalCalls: 2130,
    successRate: 97,
    avgResponseTime: 800,
    featured: false,
    verified: true,
    createdAt: '2025-08-30T12:00:00Z',
    tags: ['portfolio', 'rebalancing', 'allocation', 'strategy'],
    developer: { address: '0xDd6789Ff9012Aa1234Bb7890Cc9012Dd6789EeFf', name: 'folioworks', agentCount: 2 },
  },
  {
    agentId: 'agent-mkt-077',
    name: 'StopLossManager',
    description: 'Intelligent stop-loss placement using volatility-adjusted and trailing methods.',
    longDescription:
      'StopLossManager goes beyond fixed percentage stops to offer ATR-based, volatility-adjusted, and chandelier stop-loss calculations. It analyzes historical price action to place stops at statistically significant levels, reducing whipsaw while maintaining downside protection.',
    specialization: 'trading',
    tools: ['atr-calculator', 'stop-placer', 'whipsaw-analyzer'],
    pricing: { perCall: 4, subscription: null },
    rating: 4.2,
    reviewCount: 49,
    totalCalls: 3780,
    successRate: 94,
    avgResponseTime: 400,
    featured: false,
    verified: true,
    createdAt: '2025-10-05T14:30:00Z',
    tags: ['stop-loss', 'risk-management', 'trailing', 'trading'],
    developer: { address: '0xEe7890Aa0123Bb2345Cc8901Dd0123Ee7890FfAa', name: 'tradecraft.io', agentCount: 4 },
  },

  // ── AI / ML ───────────────────────────────────────────
  {
    agentId: 'agent-mkt-078',
    name: 'ModelEvaluator',
    description: 'Benchmarks AI/ML models for crypto prediction accuracy and reliability.',
    longDescription:
      'ModelEvaluator provides standardized benchmarking for crypto-focused AI models. It tests price prediction accuracy, sentiment analysis quality, and anomaly detection precision using curated test datasets. Produces detailed performance reports with confidence intervals and comparison against baseline models.',
    specialization: 'ai-ml',
    tools: ['benchmark-runner', 'metrics-calculator', 'report-generator'],
    pricing: { perCall: 12, subscription: null },
    rating: 4.3,
    reviewCount: 25,
    totalCalls: 430,
    successRate: 96,
    avgResponseTime: 3500,
    featured: false,
    verified: true,
    createdAt: '2025-11-25T11:00:00Z',
    tags: ['ai', 'benchmarking', 'model-evaluation', 'ml'],
    developer: { address: '0xFf8901Bb1234Cc3456Dd9012Ee1234Ff8901AaBb', name: 'mlchain.dev', agentCount: 3 },
  },
  {
    agentId: 'agent-mkt-079',
    name: 'PromptOptimizer',
    description: 'Optimizes prompts for crypto AI agents to improve output quality and consistency.',
    longDescription:
      'PromptOptimizer takes existing agent prompts and iteratively refines them for better performance. It A/B tests prompt variations against evaluation criteria, identifies failure modes, and suggests structured prompt templates optimized for common crypto agent tasks (analysis, trading signals, research).',
    specialization: 'ai-ml',
    tools: ['prompt-tester', 'ab-evaluator', 'template-generator'],
    pricing: { perCall: 8, subscription: null },
    rating: 4.1,
    reviewCount: 32,
    totalCalls: 670,
    successRate: 93,
    avgResponseTime: 2000,
    featured: false,
    verified: false,
    createdAt: '2026-01-05T15:00:00Z',
    tags: ['prompts', 'optimization', 'ai-agents', 'quality'],
    developer: { address: '0xAa9012Cc2345Dd4567Ee0123Ff2345Aa9012BbCc', name: 'mlchain.dev', agentCount: 3 },
  },
  {
    agentId: 'agent-mkt-080',
    name: 'AgentBenchmarker',
    description: 'Compares AI agent performance across standardized crypto task suites.',
    longDescription:
      'AgentBenchmarker runs AI agents through standardized task suites covering market analysis, risk assessment, portfolio management, and research. It measures accuracy, latency, cost-efficiency, and hallucination rates, producing leaderboard rankings that help users choose the best agent for each use case.',
    specialization: 'ai-ml',
    tools: ['task-runner', 'leaderboard-engine', 'hallucination-detector'],
    pricing: { perCall: 15, subscription: 200 },
    rating: 4.4,
    reviewCount: 19,
    totalCalls: 310,
    successRate: 95,
    avgResponseTime: 4500,
    featured: false,
    verified: true,
    createdAt: '2025-12-28T10:00:00Z',
    tags: ['benchmarking', 'ai-agents', 'comparison', 'leaderboard'],
    developer: { address: '0xBb0123Dd3456Ee5678Ff1234Aa3456Bb0123CcDd', name: 'agentrank.io', agentCount: 1 },
  },
  {
    agentId: 'agent-mkt-081',
    name: 'TrainingDataCurator',
    description: 'Curates and cleans on-chain and market datasets for AI model training.',
    longDescription:
      'TrainingDataCurator helps AI developers build high-quality training datasets from blockchain data. It handles data extraction, cleaning, labeling, feature engineering, and train/test splitting for common crypto ML tasks. Supports time-series price data, on-chain metrics, social sentiment, and transaction classification datasets.',
    specialization: 'ai-ml',
    tools: ['data-extractor', 'cleaner-pipeline', 'feature-engineer'],
    pricing: { perCall: 10, subscription: 150 },
    rating: 4.0,
    reviewCount: 14,
    totalCalls: 180,
    successRate: 91,
    avgResponseTime: 4000,
    featured: false,
    verified: false,
    createdAt: '2026-02-01T09:00:00Z',
    tags: ['training-data', 'ml', 'datasets', 'curation'],
    developer: { address: '0xCc1234Ee4567Ff6789Aa2345Bb4567Cc1234DdEe', name: 'mlchain.dev', agentCount: 3 },
  },
];
