/**
 * Mock marketplace listings for development / fallback when DB is empty.
 */

export interface MockMarketplaceListing {
  agentId: string;
  name: string;
  description: string;
  longDescription: string;
  specialization: string;
  tools: string[];
  pricing: { perCall: number; subscription: number | null };
  rating: number;
  reviewCount: number;
  totalCalls: number;
  successRate: number;
  avgResponseTime: number;
  featured: boolean;
  verified: boolean;
  createdAt: string;
  tags: string[];
  developer: { address: string; name: string; agentCount: number };
}

export const MOCK_MARKETPLACE_LISTINGS: MockMarketplaceListing[] = [
  // ── DeFi ──────────────────────────────────────────────
  {
    agentId: 'agent-mkt-001',
    name: 'YieldScout',
    description: 'Finds optimal yield farming strategies across DeFi protocols.',
    longDescription:
      'YieldScout continuously monitors lending rates, LP rewards, and staking yields across 40+ DeFi protocols on Ethereum, Arbitrum, and Base. It evaluates impermanent loss risk, smart-contract audit scores, and TVL trends before recommending positions.',
    specialization: 'defi',
    tools: ['defi-scanner', 'yield-calculator', 'risk-evaluator'],
    pricing: { perCall: 15, subscription: 200 },
    rating: 4.7,
    reviewCount: 134,
    totalCalls: 2870,
    successRate: 96,
    avgResponseTime: 1200,
    featured: true,
    verified: true,
    createdAt: '2025-09-12T08:30:00Z',
    tags: ['yield', 'farming', 'lending', 'arbitrum', 'base'],
    developer: { address: '0x3a1B9c7E42fD6C8A90b5e1D34F72A8bE56c9D0a', name: 'cryptovault.eth', agentCount: 4 },
  },
  {
    agentId: 'agent-mkt-002',
    name: 'LiquidityGuard',
    description: 'Monitors liquidity pool health and alerts on rug-pull signals.',
    longDescription:
      'LiquidityGuard watches on-chain liquidity changes, ownership renounce status, and token holder concentration in real time. Sends configurable alerts when any tracked pool shows warning signals such as sudden LP withdrawals or mint-function abuse.',
    specialization: 'defi',
    tools: ['pool-monitor', 'token-scanner', 'alert-dispatcher'],
    pricing: { perCall: 10, subscription: 150 },
    rating: 4.5,
    reviewCount: 89,
    totalCalls: 1950,
    successRate: 94,
    avgResponseTime: 800,
    featured: false,
    verified: true,
    createdAt: '2025-10-03T14:15:00Z',
    tags: ['liquidity', 'rug-pull', 'security', 'alerts', 'pools'],
    developer: { address: '0x7F2c9bA8D3E14567aBC0d8E91F23456789AbCdEf', name: 'shieldops', agentCount: 2 },
  },
  {
    agentId: 'agent-mkt-003',
    name: 'BridgeOptimizer',
    description: 'Finds the cheapest and fastest cross-chain bridge route.',
    longDescription:
      'Compares fees, slippage, and estimated confirmation times across all major bridges (Stargate, Across, Hop, Synapse, LayerZero) and returns a ranked list of routes. Supports 12 chains including Ethereum, Polygon, Arbitrum, Optimism, Base, and zkSync.',
    specialization: 'defi',
    tools: ['bridge-aggregator', 'gas-estimator', 'route-optimizer'],
    pricing: { perCall: 8, subscription: null },
    rating: 4.3,
    reviewCount: 56,
    totalCalls: 1340,
    successRate: 91,
    avgResponseTime: 1500,
    featured: false,
    verified: true,
    createdAt: '2025-11-18T10:00:00Z',
    tags: ['bridge', 'cross-chain', 'gas', 'multichain'],
    developer: { address: '0xAaBbCc1234567890dDeEfF0011223344556677Aa', name: 'bridgelabs.eth', agentCount: 1 },
  },

  // ── Market Analysis ───────────────────────────────────
  {
    agentId: 'agent-mkt-004',
    name: 'WhaleTracker',
    description: 'Tracks large wallet movements and surfaces actionable signals.',
    longDescription:
      'WhaleTracker monitors the top 500 wallets by holdings for each tracked token, detects unusual transfer patterns, and correlates them with DEX order flow. Results are delivered as concise market-impact summaries with confidence scores.',
    specialization: 'market',
    tools: ['wallet-tracker', 'dex-analyzer', 'signal-scorer'],
    pricing: { perCall: 20, subscription: 350 },
    rating: 4.8,
    reviewCount: 147,
    totalCalls: 2650,
    successRate: 97,
    avgResponseTime: 950,
    featured: true,
    verified: true,
    createdAt: '2025-08-22T06:45:00Z',
    tags: ['whales', 'wallets', 'signals', 'on-chain', 'dex'],
    developer: { address: '0x1234AbCd5678EfGh9012IjKl3456MnOp7890QrSt', name: 'deepflow', agentCount: 3 },
  },
  {
    agentId: 'agent-mkt-005',
    name: 'SentimentPulse',
    description: 'Aggregates social sentiment from Twitter, Discord, and Farcaster.',
    longDescription:
      'SentimentPulse ingests posts from crypto Twitter, top Discord alpha groups, and Farcaster channels. It runs NLP sentiment analysis and produces a composite mood score per token, along with trending narrative detection and influencer activity heatmaps.',
    specialization: 'market',
    tools: ['social-scraper', 'nlp-analyzer', 'trend-detector'],
    pricing: { perCall: 12, subscription: null },
    rating: 4.2,
    reviewCount: 73,
    totalCalls: 1620,
    successRate: 89,
    avgResponseTime: 1800,
    featured: false,
    verified: true,
    createdAt: '2025-10-30T12:20:00Z',
    tags: ['sentiment', 'twitter', 'discord', 'farcaster', 'nlp'],
    developer: { address: '0xBbCcDd2345678901eEfFaA1122334455667788Bb', name: 'pulsemetrics', agentCount: 2 },
  },
  {
    agentId: 'agent-mkt-006',
    name: 'TechChartist',
    description: 'Generates technical analysis reports with chart pattern detection.',
    longDescription:
      'TechChartist applies classical and modern TA indicators (RSI, MACD, Bollinger Bands, Ichimoku, volume profile) to any token pair. It detects chart patterns (head-and-shoulders, double bottoms, wedges) and produces trade setup suggestions with entry/exit zones.',
    specialization: 'market',
    tools: ['chart-analyzer', 'pattern-detector', 'indicator-engine'],
    pricing: { perCall: 18, subscription: 250 },
    rating: 4.4,
    reviewCount: 98,
    totalCalls: 2210,
    successRate: 92,
    avgResponseTime: 1100,
    featured: false,
    verified: true,
    createdAt: '2025-09-05T09:10:00Z',
    tags: ['technical-analysis', 'charts', 'patterns', 'trading'],
    developer: { address: '0xCcDdEe3456789012fFaAbB2233445566778899Cc', name: 'chartforge', agentCount: 5 },
  },

  // ── Research ──────────────────────────────────────────
  {
    agentId: 'agent-mkt-007',
    name: 'TokenIntel',
    description: 'Deep-dives into tokenomics, team backgrounds, and roadmap viability.',
    longDescription:
      'TokenIntel produces comprehensive research reports covering supply mechanics, vesting schedules, governance structure, team LinkedIn verification, GitHub commit activity, and competitive landscape analysis. Each report includes a proprietary "Conviction Score" from 0-100.',
    specialization: 'research',
    tools: ['tokenomics-parser', 'team-verifier', 'github-analyzer'],
    pricing: { perCall: 35, subscription: 500 },
    rating: 4.9,
    reviewCount: 112,
    totalCalls: 1890,
    successRate: 98,
    avgResponseTime: 2400,
    featured: true,
    verified: true,
    createdAt: '2025-07-15T11:00:00Z',
    tags: ['research', 'tokenomics', 'due-diligence', 'fundamentals'],
    developer: { address: '0xDdEeFf4567890123aAbBcC3344556677889900Dd', name: 'labyrinth.research', agentCount: 3 },
  },
  {
    agentId: 'agent-mkt-008',
    name: 'GovWatch',
    description: 'Tracks DAO governance proposals and voting patterns.',
    longDescription:
      'GovWatch indexes Snapshot and on-chain governance proposals across 80+ DAOs. It summarizes proposal content, predicts outcomes based on historical delegate behavior, and highlights contentious votes that could impact token price.',
    specialization: 'research',
    tools: ['snapshot-indexer', 'vote-analyzer', 'proposal-summarizer'],
    pricing: { perCall: 10, subscription: null },
    rating: 4.1,
    reviewCount: 34,
    totalCalls: 680,
    successRate: 93,
    avgResponseTime: 1300,
    featured: false,
    verified: true,
    createdAt: '2025-12-01T15:30:00Z',
    tags: ['governance', 'dao', 'snapshot', 'voting', 'proposals'],
    developer: { address: '0xEeFfAa5678901234bBcCdD4455667788990011Ee', name: 'govnerd', agentCount: 1 },
  },

  // ── News ──────────────────────────────────────────────
  {
    agentId: 'agent-mkt-009',
    name: 'CryptoDigest',
    description: 'Curates the top crypto news stories and delivers concise briefs.',
    longDescription:
      'CryptoDigest pulls from 50+ news sources (CoinDesk, The Block, Decrypt, DL News, etc.), de-duplicates stories, and produces ranked daily briefs or on-demand topic summaries. Includes relevance scoring and market-impact estimates for each story.',
    specialization: 'news',
    tools: ['news-aggregator', 'dedup-engine', 'summary-writer'],
    pricing: { perCall: 5, subscription: 100 },
    rating: 4.6,
    reviewCount: 88,
    totalCalls: 2990,
    successRate: 99,
    avgResponseTime: 600,
    featured: true,
    verified: true,
    createdAt: '2025-08-01T07:00:00Z',
    tags: ['news', 'briefing', 'aggregation', 'daily-digest'],
    developer: { address: '0xFfAaBb6789012345cCdDeE5566778899001122Ff', name: 'newsflow.xyz', agentCount: 2 },
  },
  {
    agentId: 'agent-mkt-010',
    name: 'RegRadar',
    description: 'Monitors global crypto regulation updates and compliance changes.',
    longDescription:
      'RegRadar tracks regulatory filings, court rulings, and legislative proposals from the SEC, CFTC, MiCA, and 30+ other jurisdictions. It flags changes relevant to DeFi protocols, stablecoins, and token classifications and provides plain-English summaries.',
    specialization: 'news',
    tools: ['regulation-crawler', 'legal-summarizer', 'jurisdiction-mapper'],
    pricing: { perCall: 15, subscription: null },
    rating: 4.3,
    reviewCount: 41,
    totalCalls: 520,
    successRate: 95,
    avgResponseTime: 1700,
    featured: false,
    verified: true,
    createdAt: '2025-11-10T13:45:00Z',
    tags: ['regulation', 'compliance', 'sec', 'mica', 'legal'],
    developer: { address: '0xAa1122Bb3344Cc5566Dd7788Ee9900Ff0011AaBb', name: 'compliancenode', agentCount: 1 },
  },

  // ── Security ──────────────────────────────────────────
  {
    agentId: 'agent-mkt-011',
    name: 'AuditLens',
    description: 'Scans smart contracts for common vulnerabilities and code smells.',
    longDescription:
      'AuditLens performs static analysis on Solidity contracts, checking for reentrancy, unchecked external calls, integer overflows, access-control gaps, and 60+ other vulnerability patterns. Returns findings ranked by severity with remediation suggestions.',
    specialization: 'security',
    tools: ['solidity-analyzer', 'vuln-scanner', 'report-generator'],
    pricing: { perCall: 40, subscription: null },
    rating: 4.6,
    reviewCount: 67,
    totalCalls: 890,
    successRate: 97,
    avgResponseTime: 2200,
    featured: false,
    verified: true,
    createdAt: '2025-09-20T16:00:00Z',
    tags: ['audit', 'security', 'solidity', 'vulnerabilities', 'smart-contracts'],
    developer: { address: '0xBb2233Cc4455Dd6677Ee8899Ff0011Aa2233BbCc', name: 'fortressec', agentCount: 3 },
  },
  {
    agentId: 'agent-mkt-012',
    name: 'PhishGuard',
    description: 'Detects phishing links and malicious contract approvals.',
    longDescription:
      'PhishGuard maintains a real-time database of known phishing domains, drainer contracts, and malicious approval patterns. Users can submit URLs or contract addresses for instant risk assessment, and receive a detailed threat breakdown.',
    specialization: 'security',
    tools: ['url-scanner', 'approval-checker', 'threat-db'],
    pricing: { perCall: 5, subscription: null },
    rating: 4.8,
    reviewCount: 102,
    totalCalls: 2450,
    successRate: 99,
    avgResponseTime: 350,
    featured: true,
    verified: true,
    createdAt: '2025-08-10T04:20:00Z',
    tags: ['phishing', 'security', 'approvals', 'scam-detection'],
    developer: { address: '0xCc3344Dd5566Ee7788Ff9900Aa1122Bb3344CcDd', name: 'shieldwall.eth', agentCount: 2 },
  },

  // ── NFT ───────────────────────────────────────────────
  {
    agentId: 'agent-mkt-013',
    name: 'FloorSweep',
    description: 'Tracks NFT collection floor prices and identifies undervalued listings.',
    longDescription:
      'FloorSweep monitors OpenSea, Blur, and Magic Eden for floor price changes across 500+ collections. It identifies trait-based undervaluations, alerts on sudden floor drops, and provides collection momentum scores based on volume and unique buyer trends.',
    specialization: 'nft',
    tools: ['nft-indexer', 'trait-analyzer', 'price-tracker'],
    pricing: { perCall: 10, subscription: null },
    rating: 4.0,
    reviewCount: 45,
    totalCalls: 1100,
    successRate: 90,
    avgResponseTime: 900,
    featured: false,
    verified: false,
    createdAt: '2025-10-15T19:30:00Z',
    tags: ['nft', 'floor-price', 'opensea', 'blur', 'collections'],
    developer: { address: '0xDd4455Ee6677Ff8899Aa0011Bb2233Cc4455DdEe', name: 'nftgrinder', agentCount: 1 },
  },
  {
    agentId: 'agent-mkt-014',
    name: 'MintRadar',
    description: 'Discovers upcoming NFT mints and evaluates hype and team legitimacy.',
    longDescription:
      'MintRadar scans Twitter, Discord announcements, and on-chain deploy events to surface upcoming mints before they trend. Each mint is scored on team credibility, art quality, community size, and smart-contract safety.',
    specialization: 'nft',
    tools: ['mint-scanner', 'hype-scorer', 'contract-checker'],
    pricing: { perCall: 8, subscription: null },
    rating: 3.8,
    reviewCount: 28,
    totalCalls: 540,
    successRate: 86,
    avgResponseTime: 1400,
    featured: false,
    verified: false,
    createdAt: '2025-12-05T21:00:00Z',
    tags: ['nft', 'minting', 'alpha', 'discovery'],
    developer: { address: '0xEe5566Ff7788Aa9900Bb1122Cc3344Dd5566EeFf', name: 'mintoor', agentCount: 1 },
  },

  // ── Gaming ────────────────────────────────────────────
  {
    agentId: 'agent-mkt-015',
    name: 'GuildManager',
    description: 'Optimizes Web3 gaming guild operations and scholarship distribution.',
    longDescription:
      'GuildManager helps gaming guilds track scholar performance, distribute earnings fairly, and identify the most profitable games. It integrates with Axie Infinity, Pixels, Big Time, and 10+ other blockchain games via their APIs.',
    specialization: 'gaming',
    tools: ['guild-tracker', 'earnings-splitter', 'game-api-hub'],
    pricing: { perCall: 12, subscription: 180 },
    rating: 3.9,
    reviewCount: 22,
    totalCalls: 380,
    successRate: 88,
    avgResponseTime: 1600,
    featured: false,
    verified: false,
    createdAt: '2025-11-25T08:15:00Z',
    tags: ['gaming', 'guild', 'scholarship', 'play-to-earn'],
    developer: { address: '0xFf6677Aa8899Bb0011Cc2233Dd4455Ee6677FfAa', name: 'guildmaster.gg', agentCount: 2 },
  },
  {
    agentId: 'agent-mkt-016',
    name: 'LootOracle',
    description: 'Prices in-game items and suggests optimal trade windows.',
    longDescription:
      'LootOracle tracks in-game asset prices across major blockchain gaming marketplaces. It applies historical price analysis to predict short-term trends and recommends buy/sell timing for rare items, land plots, and consumables.',
    specialization: 'gaming',
    tools: ['item-pricer', 'marketplace-scraper', 'trend-predictor'],
    pricing: { perCall: 7, subscription: null },
    rating: 3.7,
    reviewCount: 15,
    totalCalls: 230,
    successRate: 85,
    avgResponseTime: 1100,
    featured: false,
    verified: false,
    createdAt: '2026-01-08T17:40:00Z',
    tags: ['gaming', 'loot', 'items', 'marketplace', 'pricing'],
    developer: { address: '0xAa7788Bb9900Cc1122Dd3344Ee5566Ff7788AaBb', name: 'lootlabs', agentCount: 1 },
  },

  // ── Education ─────────────────────────────────────────
  {
    agentId: 'agent-mkt-017',
    name: 'SolidityTutor',
    description: 'Interactive Solidity learning assistant with exercises and code review.',
    longDescription:
      'SolidityTutor provides structured lessons from beginner to advanced Solidity development. It offers coding exercises, reviews submitted contracts, explains gas optimizations, and quizzes users on security best practices. Tracks learning progress across sessions.',
    specialization: 'education',
    tools: ['lesson-engine', 'code-reviewer', 'quiz-generator'],
    pricing: { perCall: 5, subscription: 100 },
    rating: 4.7,
    reviewCount: 63,
    totalCalls: 1750,
    successRate: 99,
    avgResponseTime: 500,
    featured: false,
    verified: true,
    createdAt: '2025-10-01T10:30:00Z',
    tags: ['education', 'solidity', 'learning', 'smart-contracts', 'coding'],
    developer: { address: '0xBb8899Cc0011Dd2233Ee4455Ff6677Aa8899BbCc', name: 'learnchain.dev', agentCount: 4 },
  },
  {
    agentId: 'agent-mkt-018',
    name: 'DeFiExplainer',
    description: 'Breaks down complex DeFi concepts into beginner-friendly explanations.',
    longDescription:
      'DeFiExplainer answers questions about any DeFi protocol, mechanism, or term in plain language. It can walk through specific transactions to show how protocols work under the hood, and provides visual diagrams of token flows.',
    specialization: 'education',
    tools: ['concept-mapper', 'tx-decoder', 'diagram-generator'],
    pricing: { perCall: 5, subscription: null },
    rating: 4.5,
    reviewCount: 48,
    totalCalls: 1280,
    successRate: 97,
    avgResponseTime: 700,
    featured: false,
    verified: true,
    createdAt: '2025-11-12T09:00:00Z',
    tags: ['education', 'defi', 'explainer', 'beginner', 'tutorials'],
    developer: { address: '0xCc9900Dd1122Ee3344Ff5566Aa7788Bb9900CcDd', name: 'learnchain.dev', agentCount: 4 },
  },

  // ── Health ────────────────────────────────────────────
  {
    agentId: 'agent-mkt-019',
    name: 'WellnessOracle',
    description: 'Provides personalized wellness tips based on on-chain activity patterns.',
    longDescription:
      'WellnessOracle analyzes a wallet\'s transaction timestamps to detect unhealthy trading patterns (sleep-deprived trading, revenge trading after losses, excessive screen time). It offers evidence-based wellness suggestions and can set "cool-down" reminders.',
    specialization: 'health',
    tools: ['activity-analyzer', 'pattern-detector', 'reminder-scheduler'],
    pricing: { perCall: 5, subscription: null },
    rating: 4.1,
    reviewCount: 19,
    totalCalls: 310,
    successRate: 93,
    avgResponseTime: 450,
    featured: false,
    verified: false,
    createdAt: '2026-01-15T14:00:00Z',
    tags: ['health', 'wellness', 'mindfulness', 'trading-habits'],
    developer: { address: '0xDd0011Ee2233Ff4455Aa6677Bb8899Cc0011DdEe', name: 'zentrader', agentCount: 1 },
  },

  // ── Legal ─────────────────────────────────────────────
  {
    agentId: 'agent-mkt-020',
    name: 'TaxHelper',
    description: 'Generates preliminary crypto tax reports from on-chain history.',
    longDescription:
      'TaxHelper ingests wallet addresses, traces all swaps, bridges, staking rewards, and airdrops, and categorizes each event by tax treatment (capital gains, income, etc.). Exports CSV reports compatible with TurboTax, Koinly, and CoinTracker.',
    specialization: 'legal',
    tools: ['tx-classifier', 'cost-basis-calculator', 'csv-exporter'],
    pricing: { perCall: 25, subscription: 300 },
    rating: 4.4,
    reviewCount: 77,
    totalCalls: 1560,
    successRate: 94,
    avgResponseTime: 2500,
    featured: false,
    verified: true,
    createdAt: '2025-09-28T11:30:00Z',
    tags: ['tax', 'legal', 'reporting', 'accounting', 'compliance'],
    developer: { address: '0xEe1122Ff3344Aa5566Bb7788Cc9900Dd1122EeFf', name: 'taxnodes', agentCount: 2 },
  },

  // ── Media / Creative ──────────────────────────────────
  {
    agentId: 'agent-mkt-021',
    name: 'NFTArtGen',
    description: 'Generates trait-based generative art collections from text prompts.',
    longDescription:
      'NFTArtGen creates layered generative art suitable for PFP collections. Users describe styles, color palettes, and trait categories; the agent produces sample outputs and full collection metadata. Supports ERC-721 and ERC-1155 metadata standards.',
    specialization: 'creative',
    tools: ['art-generator', 'trait-combiner', 'metadata-builder'],
    pricing: { perCall: 30, subscription: null },
    rating: 4.2,
    reviewCount: 36,
    totalCalls: 470,
    successRate: 91,
    avgResponseTime: 2300,
    featured: false,
    verified: false,
    createdAt: '2025-12-20T18:00:00Z',
    tags: ['creative', 'generative-art', 'nft', 'pfp', 'collections'],
    developer: { address: '0xFf2233Aa4455Bb6677Cc8899Dd0011Ee2233FfAa', name: 'pixelalchemy', agentCount: 1 },
  },
  {
    agentId: 'agent-mkt-022',
    name: 'ThreadCraft',
    description: 'Drafts engaging crypto Twitter threads from research notes.',
    longDescription:
      'ThreadCraft takes raw research notes, data points, or article links and transforms them into well-structured Twitter/X threads optimized for engagement. It suggests hook tweets, adds relevant emojis and formatting, and recommends posting times based on follower timezone analysis.',
    specialization: 'media',
    tools: ['thread-writer', 'engagement-optimizer', 'schedule-advisor'],
    pricing: { perCall: 8, subscription: null },
    rating: 4.0,
    reviewCount: 52,
    totalCalls: 980,
    successRate: 96,
    avgResponseTime: 800,
    featured: false,
    verified: false,
    createdAt: '2025-11-05T20:15:00Z',
    tags: ['media', 'twitter', 'threads', 'content', 'marketing'],
    developer: { address: '0xAa3344Bb5566Cc7788Dd9900Ee1122Ff3344AaBb', name: 'viralnode', agentCount: 2 },
  },

  // ── Utility ───────────────────────────────────────────
  {
    agentId: 'agent-mkt-023',
    name: 'GasOracle',
    description: 'Predicts optimal gas prices and recommends transaction timing.',
    longDescription:
      'GasOracle uses historical block data and mempool analysis to predict gas prices 1-30 minutes ahead. It recommends optimal submission times for non-urgent transactions and can estimate costs for complex contract interactions.',
    specialization: 'utility',
    tools: ['gas-predictor', 'mempool-analyzer', 'cost-estimator'],
    pricing: { perCall: 5, subscription: null },
    rating: 4.5,
    reviewCount: 131,
    totalCalls: 2800,
    successRate: 95,
    avgResponseTime: 200,
    featured: false,
    verified: true,
    createdAt: '2025-08-18T05:00:00Z',
    tags: ['gas', 'utility', 'optimization', 'ethereum', 'transactions'],
    developer: { address: '0xBb4455Cc6677Dd8899Ee0011Ff2233Aa4455BbCc', name: 'gasworks.eth', agentCount: 1 },
  },
  {
    agentId: 'agent-mkt-024',
    name: 'ENSResolver',
    description: 'Resolves ENS names, checks availability, and suggests alternatives.',
    longDescription:
      'ENSResolver provides instant ENS name lookups, availability checks, and registration cost estimates. It can suggest similar available names when a desired name is taken, and tracks expiring premium names that may become available soon.',
    specialization: 'utility',
    tools: ['ens-lookup', 'name-suggester', 'expiry-tracker'],
    pricing: { perCall: 5, subscription: null },
    rating: 4.3,
    reviewCount: 39,
    totalCalls: 920,
    successRate: 98,
    avgResponseTime: 300,
    featured: false,
    verified: true,
    createdAt: '2025-10-22T12:00:00Z',
    tags: ['ens', 'domains', 'naming', 'utility', 'identity'],
    developer: { address: '0xCc5566Dd7788Ee9900Ff1122Aa3344Bb5566CcDd', name: 'namesmith', agentCount: 1 },
  },
  {
    agentId: 'agent-mkt-025',
    name: 'PortfolioLens',
    description: 'Aggregates multi-chain portfolio balances into a unified dashboard view.',
    longDescription:
      'PortfolioLens connects to 15+ chains and aggregates token balances, NFT holdings, DeFi positions, and unclaimed airdrops into a single view. It calculates historical PnL, tracks cost basis, and highlights concentration risks.',
    specialization: 'utility',
    tools: ['multi-chain-indexer', 'portfolio-tracker', 'pnl-calculator'],
    pricing: { perCall: 10, subscription: 150 },
    rating: 4.6,
    reviewCount: 85,
    totalCalls: 2100,
    successRate: 93,
    avgResponseTime: 1400,
    featured: false,
    verified: true,
    createdAt: '2025-09-15T08:00:00Z',
    tags: ['portfolio', 'tracking', 'multi-chain', 'pnl', 'dashboard'],
    developer: { address: '0xDd6677Ee8899Ff0011Aa2233Bb4455Cc6677DdEe', name: 'folioworks', agentCount: 2 },
  },

  // ── Additional diverse agents ─────────────────────────
  {
    agentId: 'agent-mkt-026',
    name: 'AirdropHunter',
    description: 'Identifies potential airdrop opportunities and eligibility criteria.',
    longDescription:
      'AirdropHunter monitors protocol activity, testnet launches, and governance participation across emerging projects to predict likely airdrop campaigns. It checks wallet eligibility against known criteria and suggests actions to qualify for upcoming drops.',
    specialization: 'research',
    tools: ['protocol-scanner', 'eligibility-checker', 'action-planner'],
    pricing: { perCall: 15, subscription: null },
    rating: 4.1,
    reviewCount: 94,
    totalCalls: 1870,
    successRate: 87,
    avgResponseTime: 1000,
    featured: false,
    verified: false,
    createdAt: '2025-10-08T16:30:00Z',
    tags: ['airdrops', 'alpha', 'eligibility', 'farming'],
    developer: { address: '0xEe7788Ff9900Aa1122Bb3344Cc5566Dd7788EeFf', name: 'dropzone', agentCount: 3 },
  },
  {
    agentId: 'agent-mkt-027',
    name: 'MEVShield',
    description: 'Protects transactions from MEV extraction and sandwich attacks.',
    longDescription:
      'MEVShield analyzes pending transactions for sandwich attack vulnerability, recommends optimal slippage settings, and can route transactions through private mempools (Flashbots Protect, MEV Blocker) to prevent frontrunning.',
    specialization: 'security',
    tools: ['mev-analyzer', 'private-tx-router', 'slippage-optimizer'],
    pricing: { perCall: 10, subscription: null },
    rating: 4.5,
    reviewCount: 58,
    totalCalls: 1340,
    successRate: 96,
    avgResponseTime: 250,
    featured: false,
    verified: true,
    createdAt: '2025-09-30T07:15:00Z',
    tags: ['mev', 'security', 'frontrunning', 'flashbots', 'protection'],
    developer: { address: '0xFf8899Aa0011Bb2233Cc4455Dd6677Ee8899FfAa', name: 'darkforest.dev', agentCount: 2 },
  },
  {
    agentId: 'agent-mkt-028',
    name: 'StableScan',
    description: 'Monitors stablecoin peg health and reserve transparency.',
    longDescription:
      'StableScan tracks peg deviations across all major stablecoins (USDC, USDT, DAI, FRAX, GHO, etc.) on CEX and DEX venues. It monitors reserve attestation reports, flags custody risks, and sends alerts when depeg events exceed configurable thresholds.',
    specialization: 'defi',
    tools: ['peg-monitor', 'reserve-tracker', 'depeg-alerter'],
    pricing: { perCall: 8, subscription: null },
    rating: 4.4,
    reviewCount: 42,
    totalCalls: 760,
    successRate: 98,
    avgResponseTime: 400,
    featured: false,
    verified: true,
    createdAt: '2025-11-28T13:00:00Z',
    tags: ['stablecoins', 'defi', 'peg', 'reserves', 'monitoring'],
    developer: { address: '0xAaBb0011CcDd2233EeFf4455667788990011AaBb', name: 'pegwatch', agentCount: 1 },
  },
  {
    agentId: 'agent-mkt-029',
    name: 'ContractDeployer',
    description: 'Assists with deploying and verifying smart contracts across chains.',
    longDescription:
      'ContractDeployer guides users through contract deployment on any EVM chain. It handles constructor arguments, deterministic deployments via CREATE2, source verification on block explorers, and proxy pattern setup (UUPS, Transparent). Supports Hardhat and Foundry project formats.',
    specialization: 'utility',
    tools: ['deploy-helper', 'verifier', 'proxy-setup'],
    pricing: { perCall: 20, subscription: null },
    rating: 4.3,
    reviewCount: 31,
    totalCalls: 420,
    successRate: 92,
    avgResponseTime: 1900,
    featured: false,
    verified: false,
    createdAt: '2025-12-10T10:45:00Z',
    tags: ['deployment', 'smart-contracts', 'verification', 'utility', 'evm'],
    developer: { address: '0xBbCc1122DdEe3344FfAa55667788990011BbCc22', name: 'deployoor', agentCount: 1 },
  },
  {
    agentId: 'agent-mkt-030',
    name: 'AlphaStream',
    description: 'Real-time on-chain alpha feed with configurable signal filters.',
    longDescription:
      'AlphaStream surfaces unusual on-chain activity in real time: large token unlocks, whale accumulation, new liquidity pool creation, governance attacks, and contract upgrades. Users configure signal types and minimum impact thresholds to reduce noise.',
    specialization: 'market',
    tools: ['chain-listener', 'signal-filter', 'alert-engine'],
    pricing: { perCall: 25, subscription: 400 },
    rating: 4.7,
    reviewCount: 69,
    totalCalls: 1430,
    successRate: 93,
    avgResponseTime: 350,
    featured: false,
    verified: true,
    createdAt: '2025-10-18T06:00:00Z',
    tags: ['alpha', 'signals', 'on-chain', 'real-time', 'alerts'],
    developer: { address: '0xCcDd2233EeFf4455AaBb66778899001122CcDd33', name: 'alphaforge', agentCount: 3 },
  },
];
