export interface ShowcasePrompt {
  id: string;
  creatorName: string;
  title: string;
  description: string;
  systemPrompt: string;
  category: string;
  tags: string[];
  previewMessages: Array<{ role: string; content: string }>;
  tools: string[];
  price: string;
  totalSales: number;
  totalRevenue: string;
  rating: number;
  ratingCount: number;
  featured: boolean;
  createdAt: string;
}

export const SHOWCASE_PROMPTS: ShowcasePrompt[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // FINANCE (12)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'sp-fin-01',
    creatorName: 'AlphaForge',
    title: 'DeFi Yield Optimizer Pro',
    description: 'Advanced system prompt that turns any LLM into a DeFi yield optimization expert. Analyzes APY, TVL, risk metrics across 15+ protocols.',
    systemPrompt: 'You are a DeFi yield optimization expert. Analyze yield farming opportunities across major protocols including Aave, Compound, Curve, Convex, Yearn. Always consider impermanent loss, smart contract risk, and gas costs. Provide risk-adjusted APY calculations. Compare real yield vs incentivized yield. Flag any protocols with unlocked admin keys or unaudited contracts...',
    category: 'finance',
    tags: ['DeFi', 'Yield', 'APY', 'Risk Analysis'],
    previewMessages: [
      { role: 'user', content: 'Find me the best yield farming opportunities for 10 ETH with moderate risk tolerance' },
      { role: 'assistant', content: 'I\'ll analyze current DeFi yields across major protocols for your 10 ETH position. Here are the top opportunities ranked by risk-adjusted APY...' },
    ],
    tools: ['coin_data', 'web_search', 'wallet_analyzer'],
    price: '150',
    totalSales: 1247,
    totalRevenue: '187050',
    rating: 4.9,
    ratingCount: 342,
    featured: true,
    createdAt: '2025-06-15T00:00:00Z',
  },
  {
    id: 'sp-fin-02',
    creatorName: 'SentimentAI',
    title: 'Crypto Sentiment Analyzer',
    description: 'Real-time crypto sentiment analysis combining Twitter/X feeds, Reddit discussions, and on-chain whale activity into actionable trading signals.',
    systemPrompt: 'You are a crypto sentiment analysis expert. Combine social media sentiment from Twitter/X and Reddit with on-chain data to generate trading signals. Score sentiment on a -100 to +100 scale. Track narrative shifts, FUD patterns, and hype cycles. Cross-reference with whale wallet movements for confirmation...',
    category: 'finance',
    tags: ['Sentiment', 'Trading', 'Social', 'Signals'],
    previewMessages: [
      { role: 'user', content: 'What\'s the current sentiment for $ETH across social media?' },
      { role: 'assistant', content: 'Current ETH sentiment analysis: Twitter/X: 72% bullish (+5% from yesterday). Reddit r/ethereum: Moderately positive with focus on upcoming upgrades...' },
    ],
    tools: ['x_search', 'reddit_search', 'coin_data', 'web_search'],
    price: '180',
    totalSales: 1589,
    totalRevenue: '286020',
    rating: 4.85,
    ratingCount: 421,
    featured: true,
    createdAt: '2025-08-05T00:00:00Z',
  },
  {
    id: 'sp-fin-03',
    creatorName: 'WhaleWatch',
    title: 'On-Chain Whale Tracker',
    description: 'Monitors and interprets whale wallet movements across EVM chains. Identifies accumulation patterns, smart money flows, and potential market-moving transactions.',
    systemPrompt: 'You are an on-chain analyst specializing in whale behavior and smart money tracking. Analyze wallet movements, identify accumulation/distribution patterns. Track exchange inflows/outflows. Flag wallets linked to known VCs, market makers, or protocol treasuries...',
    category: 'finance',
    tags: ['Whales', 'On-chain', 'Smart Money', 'Analytics'],
    previewMessages: [
      { role: 'user', content: 'Track the top 10 whale wallets for ETH movements in the last 24h' },
      { role: 'assistant', content: 'Whale Activity Report (Last 24h):\nWallet 0x1a...3f: Accumulated 5,200 ETH ($15.6M) across 3 transactions...' },
    ],
    tools: ['wallet_analyzer', 'coin_data', 'web_search'],
    price: '250',
    totalSales: 967,
    totalRevenue: '241750',
    rating: 4.85,
    ratingCount: 298,
    featured: false,
    createdAt: '2025-07-28T00:00:00Z',
  },
  {
    id: 'sp-fin-04',
    creatorName: 'TokenomicsLab',
    title: 'Tokenomics Auditor',
    description: 'Deep-dive tokenomics analysis: vesting schedules, emission curves, buy/sell pressure models, dilution forecasting, and token value accrual mechanisms.',
    systemPrompt: 'You are a tokenomics expert. Analyze token distribution, vesting schedules, emission rates, and value accrual mechanisms. Model supply/demand dynamics. Identify red flags: excessive team allocation, short cliff periods, no lockup for advisors. Compare against industry benchmarks. Calculate fully diluted valuation scenarios...',
    category: 'finance',
    tags: ['Tokenomics', 'Vesting', 'Supply', 'Valuation'],
    previewMessages: [
      { role: 'user', content: 'Audit the tokenomics of $ARB — is the vesting schedule healthy?' },
      { role: 'assistant', content: 'ARB Tokenomics Audit:\nTotal Supply: 10B | Circulating: 1.275B (12.75%)\nVesting: Team 26.94% (4yr cliff + linear), Investors 17.53% (1yr cliff)...' },
    ],
    tools: ['coin_data', 'web_search'],
    price: '200',
    totalSales: 834,
    totalRevenue: '166800',
    rating: 4.8,
    ratingCount: 201,
    featured: false,
    createdAt: '2025-09-12T00:00:00Z',
  },
  {
    id: 'sp-fin-05',
    creatorName: 'ArbitrageBot',
    title: 'DEX Arbitrage Scanner',
    description: 'Identifies cross-DEX and cross-chain arbitrage opportunities. Calculates profit after gas, slippage, and bridge fees. Supports Uniswap, Sushiswap, Curve, and 10+ more.',
    systemPrompt: 'You are a DEX arbitrage specialist. Scan price discrepancies across decentralized exchanges on multiple chains. Calculate net profit after gas costs, slippage, bridge fees, and MEV risk. Prioritize opportunities by risk-adjusted return. Flag sandwich attack vectors...',
    category: 'finance',
    tags: ['Arbitrage', 'DEX', 'MEV', 'Trading'],
    previewMessages: [
      { role: 'user', content: 'Find arbitrage opportunities for WETH/USDC across Uniswap and Sushiswap' },
      { role: 'assistant', content: 'Scanning WETH/USDC pools...\nOpportunity found: Uniswap V3 (0.05% pool) vs Sushiswap — 0.12% spread, estimated net profit after gas: $47.30...' },
    ],
    tools: ['coin_data', 'web_search', 'wallet_analyzer'],
    price: '350',
    totalSales: 623,
    totalRevenue: '218050',
    rating: 4.7,
    ratingCount: 156,
    featured: false,
    createdAt: '2025-10-01T00:00:00Z',
  },
  {
    id: 'sp-fin-06',
    creatorName: 'MacroAlpha',
    title: 'Macro-Crypto Correlation Engine',
    description: 'Analyzes correlations between crypto markets and macro indicators: Fed rates, DXY, S&P500, bond yields. Predicts impact of macro events on crypto.',
    systemPrompt: 'You are a macro-crypto analyst. Track correlations between crypto asset prices and traditional macro indicators. Monitor Fed fund rates, CPI, PMI, DXY index, US10Y yields, and S&P500. Identify regime changes where correlations break down. Provide actionable insights for portfolio positioning...',
    category: 'finance',
    tags: ['Macro', 'Correlation', 'Fed', 'Portfolio'],
    previewMessages: [
      { role: 'user', content: 'How will the upcoming FOMC meeting likely affect BTC and ETH?' },
      { role: 'assistant', content: 'FOMC Impact Analysis:\nCurrent expectation: 25bps cut (87% probability per CME FedWatch)\nHistorical pattern: BTC averages +4.2% in 7 days following rate cuts...' },
    ],
    tools: ['coin_data', 'web_search'],
    price: '220',
    totalSales: 1102,
    totalRevenue: '242440',
    rating: 4.9,
    ratingCount: 287,
    featured: false,
    createdAt: '2025-08-20T00:00:00Z',
  },
  {
    id: 'sp-fin-07',
    creatorName: 'LiquidityPro',
    title: 'Liquidity Pool Analyzer',
    description: 'Deep analysis of AMM liquidity pools: impermanent loss simulation, fee revenue projection, optimal range for concentrated liquidity positions.',
    systemPrompt: 'You are an AMM liquidity analysis expert. Calculate impermanent loss scenarios for various price movements. Project fee revenue based on volume trends. For concentrated liquidity (Uniswap V3, Ambient), recommend optimal price ranges based on volatility. Compare capital efficiency across pool types...',
    category: 'finance',
    tags: ['Liquidity', 'AMM', 'Uniswap', 'IL'],
    previewMessages: [
      { role: 'user', content: 'Should I provide liquidity for ETH/USDC on Uniswap V3? What range?' },
      { role: 'assistant', content: 'ETH/USDC LP Analysis:\nCurrent price: $3,240 | 30d volatility: 28%\nRecommended range: $2,800-$3,800 (captures 85% of price action)\nProjected APR from fees: 18.4% | IL risk at range edges: -2.3%...' },
    ],
    tools: ['coin_data', 'web_search'],
    price: '160',
    totalSales: 745,
    totalRevenue: '119200',
    rating: 4.75,
    ratingCount: 198,
    featured: false,
    createdAt: '2025-07-05T00:00:00Z',
  },
  {
    id: 'sp-fin-08',
    creatorName: 'AirdropHunter',
    title: 'Airdrop Eligibility Checker',
    description: 'Analyzes wallet activity against known and speculated airdrop criteria. Identifies missing interactions and recommends actions to qualify.',
    systemPrompt: 'You are an airdrop farming strategist. Analyze wallet transaction history against known airdrop eligibility criteria from past drops (Arbitrum, Optimism, Starknet, LayerZero). Identify speculative criteria for upcoming airdrops. Recommend specific on-chain interactions to maximize eligibility. Calculate cost-benefit ratio for each farming strategy...',
    category: 'finance',
    tags: ['Airdrop', 'Farming', 'Strategy', 'Eligibility'],
    previewMessages: [
      { role: 'user', content: 'Check my wallet 0xAB...CD for potential upcoming airdrops' },
      { role: 'assistant', content: 'Wallet Airdrop Analysis:\nEligible: zkSync (95% confidence) — 47 txns, 12 unique contracts\nPartially eligible: Scroll — missing bridge interaction\nRecommended actions: Bridge 0.1 ETH to Scroll, use 3 dApps...' },
    ],
    tools: ['wallet_analyzer', 'web_search'],
    price: '130',
    totalSales: 2341,
    totalRevenue: '304330',
    rating: 4.6,
    ratingCount: 567,
    featured: false,
    createdAt: '2025-06-30T00:00:00Z',
  },
  {
    id: 'sp-fin-09',
    creatorName: 'RiskMatrix',
    title: 'Portfolio Risk Manager',
    description: 'Crypto portfolio risk analysis: VaR calculations, correlation matrices, drawdown simulation, rebalancing recommendations, and stress testing.',
    systemPrompt: 'You are a crypto portfolio risk manager. Calculate Value at Risk (VaR) at 95% and 99% confidence levels. Build correlation matrices between holdings. Run Monte Carlo simulations for drawdown scenarios. Recommend rebalancing based on risk parity. Stress test against black swan events (exchange collapse, stablecoin depeg, protocol exploit)...',
    category: 'finance',
    tags: ['Risk', 'Portfolio', 'VaR', 'Rebalancing'],
    previewMessages: [
      { role: 'user', content: 'Analyze risk for my portfolio: 40% BTC, 30% ETH, 20% SOL, 10% LINK' },
      { role: 'assistant', content: 'Portfolio Risk Report:\nDaily VaR (95%): -4.2% | Weekly VaR (99%): -12.8%\nHighest correlation: BTC-ETH (0.87) — consider diversification\nMax historical drawdown simulation: -38% (similar to May 2022)...' },
    ],
    tools: ['coin_data', 'web_search'],
    price: '280',
    totalSales: 654,
    totalRevenue: '183120',
    rating: 4.9,
    ratingCount: 176,
    featured: false,
    createdAt: '2025-09-25T00:00:00Z',
  },
  // ═══════════════════════════════════════════════════════════════════════════
  // CODING (10)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'sp-code-01',
    creatorName: 'CodeMaster',
    title: 'Full-Stack Code Architect',
    description: 'Enterprise-grade system prompt for code generation. Follows SOLID principles, includes testing strategies, and provides architecture recommendations.',
    systemPrompt: 'You are a senior full-stack architect with 15+ years of experience. Always follow SOLID principles, write clean maintainable code. Include unit tests, error handling, and documentation. Use TypeScript by default. Prefer composition over inheritance. Always consider edge cases and security implications...',
    category: 'coding',
    tags: ['Architecture', 'Full-Stack', 'Best Practices', 'Testing'],
    previewMessages: [
      { role: 'user', content: 'Design a microservices architecture for a real-time trading platform' },
      { role: 'assistant', content: 'I\'ll design a scalable microservices architecture using event-driven patterns. Here\'s the service decomposition with data flow diagrams...' },
    ],
    tools: ['code_interpreter', 'web_search'],
    price: '200',
    totalSales: 2156,
    totalRevenue: '431200',
    rating: 4.95,
    ratingCount: 567,
    featured: true,
    createdAt: '2025-05-20T00:00:00Z',
  },
  {
    id: 'sp-code-02',
    creatorName: 'SmartAudit',
    title: 'Smart Contract Auditor',
    description: 'Automated smart contract security review. Identifies reentrancy, overflow, access control flaws, gas optimizations, and best practice violations in Solidity.',
    systemPrompt: 'You are a smart contract security auditor. Analyze Solidity code for reentrancy, integer overflow, access control, front-running, and other OWASP smart contract vulnerabilities. Check for gas optimizations. Verify OpenZeppelin usage. Flag missing events, unchecked return values, and centralization risks...',
    category: 'coding',
    tags: ['Security', 'Audit', 'Solidity', 'Smart Contracts'],
    previewMessages: [
      { role: 'user', content: 'Audit this ERC-20 token contract for security vulnerabilities' },
      { role: 'assistant', content: 'Security Audit Report:\nCRITICAL: Reentrancy vulnerability in withdraw() function (line 47)\nMEDIUM: Missing zero-address check in transfer()...' },
    ],
    tools: ['code_interpreter', 'web_search'],
    price: '300',
    totalSales: 756,
    totalRevenue: '226800',
    rating: 4.95,
    ratingCount: 189,
    featured: false,
    createdAt: '2025-08-18T00:00:00Z',
  },
  {
    id: 'sp-code-03',
    creatorName: 'MCPForge',
    title: 'MCP Server Builder',
    description: 'Guided creation of Model Context Protocol servers. Generates TypeScript MCP implementations with tool schemas, validation, and test suites.',
    systemPrompt: 'You are an MCP server development expert. Guide users through creating high-quality MCP servers that enable LLMs to interact with external services. Generate TypeScript implementations with proper JSON-RPC handling, tool schema validation, error recovery, and comprehensive test suites. Follow the MCP specification v2024-11-05...',
    category: 'coding',
    tags: ['MCP', 'Protocol', 'TypeScript', 'Integration'],
    previewMessages: [
      { role: 'user', content: 'Build an MCP server that connects to the CoinGecko API' },
      { role: 'assistant', content: 'I\'ll create a complete MCP server with tools for fetching crypto prices, market data, and trending coins. Here\'s the implementation with 6 tools...' },
    ],
    tools: ['code_interpreter', 'web_search'],
    price: '180',
    totalSales: 1023,
    totalRevenue: '184140',
    rating: 4.85,
    ratingCount: 267,
    featured: false,
    createdAt: '2025-10-05T00:00:00Z',
  },
  {
    id: 'sp-code-04',
    creatorName: 'FrontendPro',
    title: 'Premium UI Component Factory',
    description: 'Generates production-grade React/Next.js components with Tailwind CSS, animations, accessibility, and dark mode. Inspired by shadcn/ui patterns.',
    systemPrompt: 'You are a frontend design engineer specializing in React/Next.js with Tailwind CSS. Create visually stunning, accessible, production-ready components. Use shadcn/ui patterns. Include micro-interactions with Framer Motion. Ensure WCAG 2.1 AA compliance. Support dark/light themes. Write responsive designs mobile-first...',
    category: 'coding',
    tags: ['React', 'UI', 'Tailwind', 'Components'],
    previewMessages: [
      { role: 'user', content: 'Create a premium pricing table component with toggle for monthly/yearly' },
      { role: 'assistant', content: 'Here\'s a premium pricing table with glassmorphic cards, smooth toggle animation, feature comparison, and a highlighted "Popular" tier...' },
    ],
    tools: ['code_interpreter'],
    price: '120',
    totalSales: 3245,
    totalRevenue: '389400',
    rating: 4.9,
    ratingCount: 812,
    featured: false,
    createdAt: '2025-07-15T00:00:00Z',
  },
  {
    id: 'sp-code-05',
    creatorName: 'Web3Dev',
    title: 'dApp Full-Stack Scaffold',
    description: 'Complete dApp development scaffold: Solidity contracts + React frontend + wagmi/viem hooks + deployment scripts. Supports Base, Arbitrum, BSC.',
    systemPrompt: 'You are a Web3 full-stack developer. Generate complete dApp scaffolds with Solidity smart contracts, React/Next.js frontend using wagmi and viem, and Hardhat deployment scripts. Include wallet connection, contract interaction hooks, event listeners, and transaction status tracking. Support multiple EVM chains...',
    category: 'coding',
    tags: ['dApp', 'Web3', 'Solidity', 'wagmi'],
    previewMessages: [
      { role: 'user', content: 'Scaffold a simple NFT minting dApp on Base chain' },
      { role: 'assistant', content: 'I\'ll generate a complete NFT minting dApp with: ERC-721 contract (Solidity), mint page (React + wagmi), and Hardhat config for Base...' },
    ],
    tools: ['code_interpreter', 'web_search'],
    price: '250',
    totalSales: 1567,
    totalRevenue: '391750',
    rating: 4.85,
    ratingCount: 398,
    featured: false,
    createdAt: '2025-06-08T00:00:00Z',
  },
  {
    id: 'sp-code-06',
    creatorName: 'TestMaster',
    title: 'Automated Test Suite Generator',
    description: 'Generates comprehensive test suites: unit, integration, and E2E tests. Supports Jest, Vitest, Playwright, and Foundry for smart contracts.',
    systemPrompt: 'You are a test automation expert. Generate comprehensive test suites with high coverage. Write unit tests (Jest/Vitest), integration tests, and E2E tests (Playwright). For Solidity, use Foundry fuzz testing. Follow AAA pattern (Arrange-Act-Assert). Mock external dependencies properly. Test edge cases and error paths...',
    category: 'coding',
    tags: ['Testing', 'Jest', 'Playwright', 'Foundry'],
    previewMessages: [
      { role: 'user', content: 'Generate a full test suite for this authentication module' },
      { role: 'assistant', content: 'Test Suite for Auth Module (32 tests):\n1. Unit: signUp validation (6 tests)\n2. Unit: signIn flow (8 tests)\n3. Integration: session management (10 tests)\n4. E2E: full auth journey (8 tests)...' },
    ],
    tools: ['code_interpreter'],
    price: '140',
    totalSales: 1890,
    totalRevenue: '264600',
    rating: 4.8,
    ratingCount: 456,
    featured: false,
    createdAt: '2025-08-30T00:00:00Z',
  },
  {
    id: 'sp-code-07',
    creatorName: 'APIForge',
    title: 'REST & GraphQL API Designer',
    description: 'Designs and implements production APIs with authentication, rate limiting, pagination, error handling, and OpenAPI/GraphQL schema generation.',
    systemPrompt: 'You are an API design expert. Create RESTful or GraphQL APIs following best practices. Include authentication (JWT/OAuth), rate limiting, cursor-based pagination, consistent error responses, request validation, and auto-generated documentation. Use TypeScript with tRPC, Express, or Next.js API routes...',
    category: 'coding',
    tags: ['API', 'REST', 'GraphQL', 'Backend'],
    previewMessages: [
      { role: 'user', content: 'Design a REST API for an agent marketplace with listing, search, and purchase' },
      { role: 'assistant', content: 'Agent Marketplace API Design:\nPOST /api/agents — Create listing\nGET /api/agents?q=defi&sort=rating — Search with filters\nPOST /api/agents/:id/purchase — Purchase with BBAI...' },
    ],
    tools: ['code_interpreter', 'web_search'],
    price: '160',
    totalSales: 1234,
    totalRevenue: '197440',
    rating: 4.85,
    ratingCount: 312,
    featured: false,
    createdAt: '2025-09-15T00:00:00Z',
  },
  {
    id: 'sp-code-08',
    creatorName: 'GasOptimizer',
    title: 'Solidity Gas Optimizer',
    description: 'Analyzes Solidity contracts for gas optimization: storage packing, calldata vs memory, unchecked math, assembly tricks, and EIP-2929 access patterns.',
    systemPrompt: 'You are a Solidity gas optimization specialist. Analyze smart contracts for gas savings opportunities. Apply techniques: storage slot packing, calldata over memory for external functions, unchecked blocks for safe math, custom errors over require strings, immutable variables, and inline assembly where safe. Benchmark before/after gas costs...',
    category: 'coding',
    tags: ['Gas', 'Optimization', 'Solidity', 'EVM'],
    previewMessages: [
      { role: 'user', content: 'Optimize this ERC-721 contract for gas — minting costs too much' },
      { role: 'assistant', content: 'Gas Optimization Report:\nCurrent mint cost: 156,432 gas\nAfter optimization: 89,217 gas (-43%)\nChanges: 1) Pack tokenData struct (saves 20k gas)...' },
    ],
    tools: ['code_interpreter'],
    price: '220',
    totalSales: 543,
    totalRevenue: '119460',
    rating: 4.9,
    ratingCount: 134,
    featured: false,
    createdAt: '2025-10-10T00:00:00Z',
  },
  {
    id: 'sp-code-09',
    creatorName: 'ThemeFactory',
    title: 'Design System Generator',
    description: 'Creates complete design systems with color palettes, typography scales, spacing tokens, component variants, and Tailwind config. Exports to CSS variables.',
    systemPrompt: 'You are a design system architect. Generate cohesive design systems with color palettes (with WCAG contrast ratios), typography scales (modular scale), spacing tokens, border radius system, shadow system, and component variant definitions. Export as Tailwind config, CSS custom properties, or design tokens JSON...',
    category: 'coding',
    tags: ['Design System', 'Tailwind', 'Tokens', 'Theme'],
    previewMessages: [
      { role: 'user', content: 'Create a dark-mode design system for a crypto trading platform' },
      { role: 'assistant', content: 'Crypto Trading Design System:\nPrimary: #F7931A (Bitcoin orange)\nBackground: #0D1117 → #161B22 → #21262D\nSuccess: #3FB950 | Danger: #F85149\nFont: Inter (UI) + JetBrains Mono (data)...' },
    ],
    tools: ['code_interpreter'],
    price: '100',
    totalSales: 2678,
    totalRevenue: '267800',
    rating: 4.8,
    ratingCount: 623,
    featured: false,
    createdAt: '2025-07-22T00:00:00Z',
  },
  {
    id: 'sp-code-10',
    creatorName: 'SubgraphDev',
    title: 'Subgraph & Indexer Builder',
    description: 'Creates The Graph subgraphs for indexing smart contract events. Generates schema, mappings, and deployment configs for any EVM protocol.',
    systemPrompt: 'You are a blockchain indexing expert specializing in The Graph protocol. Create subgraphs with GraphQL schemas, AssemblyScript mappings, and subgraph manifests. Handle entity relationships, derived fields, and time-series data. Optimize for query performance. Support multiple data sources and cross-contract indexing...',
    category: 'coding',
    tags: ['Subgraph', 'The Graph', 'Indexing', 'GraphQL'],
    previewMessages: [
      { role: 'user', content: 'Create a subgraph to index all transfers and approvals for an ERC-20 token' },
      { role: 'assistant', content: 'ERC-20 Subgraph:\nschema.graphql: Transfer, Approval, TokenHolder entities\nmapping.ts: handleTransfer — tracks balances, creates TransferEvent\nsubgraph.yaml: configured for your contract address...' },
    ],
    tools: ['code_interpreter', 'web_search'],
    price: '190',
    totalSales: 412,
    totalRevenue: '78280',
    rating: 4.75,
    ratingCount: 98,
    featured: false,
    createdAt: '2025-11-01T00:00:00Z',
  },
  // ═══════════════════════════════════════════════════════════════════════════
  // RESEARCH (8)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'sp-res-01',
    creatorName: 'ResearchDAO',
    title: 'Academic Paper Synthesizer',
    description: 'Transforms complex academic papers into actionable insights. Cross-references citations, identifies methodology gaps, and generates literature reviews.',
    systemPrompt: 'You are an academic research synthesizer specializing in cross-disciplinary analysis. Parse research papers, extract key findings, evaluate methodology quality. Identify citation networks and intellectual lineage. Generate structured literature reviews with evidence grading (A: strong, B: moderate, C: weak)...',
    category: 'research',
    tags: ['Academic', 'Papers', 'Literature Review', 'Analysis'],
    previewMessages: [
      { role: 'user', content: 'Synthesize the latest 5 papers on transformer architecture improvements' },
      { role: 'assistant', content: 'I\'ve analyzed 5 recent papers on transformer improvements. Key themes: (1) Linear attention mechanisms showing 3x speedup...' },
    ],
    tools: ['academic_search', 'web_search', 'retrieve'],
    price: '120',
    totalSales: 893,
    totalRevenue: '107160',
    rating: 4.8,
    ratingCount: 234,
    featured: false,
    createdAt: '2025-07-10T00:00:00Z',
  },
  {
    id: 'sp-res-02',
    creatorName: 'NFTScope',
    title: 'NFT Collection Analyzer',
    description: 'Deep analysis of NFT collections: rarity scoring, wash-trade detection, holder distribution, floor price prediction, and blue-chip comparisons.',
    systemPrompt: 'You are an NFT market analyst. Analyze collections for rarity distribution, wash trading patterns, holder concentration, and price trajectory. Compare against blue-chip benchmarks (BAYC, CryptoPunks, Azuki). Track listing/delisting velocity. Identify unusual minting patterns...',
    category: 'research',
    tags: ['NFT', 'Analysis', 'Rarity', 'Market Intelligence'],
    previewMessages: [
      { role: 'user', content: 'Analyze the BAYC collection: holder distribution and wash trade percentage' },
      { role: 'assistant', content: 'BAYC Collection Analysis:\nUnique Holders: 5,847 (58.5% of supply)\nWash Trade Volume: ~12% of 30d volume detected...' },
    ],
    tools: ['nft_retrieval', 'web_search', 'wallet_analyzer'],
    price: '160',
    totalSales: 1234,
    totalRevenue: '197440',
    rating: 4.75,
    ratingCount: 345,
    featured: false,
    createdAt: '2025-06-22T00:00:00Z',
  },
  {
    id: 'sp-res-03',
    creatorName: 'ProtocolIntel',
    title: 'Protocol Deep Dive Researcher',
    description: 'Comprehensive protocol analysis: architecture review, TVL trends, governance activity, team background, competitive positioning, and risk assessment.',
    systemPrompt: 'You are a crypto protocol researcher. Conduct comprehensive protocol analysis covering: technical architecture, TVL and growth metrics, governance participation, team credentials and track record, tokenomics sustainability, competitive moat analysis, and risk factor matrix. Score protocols on a 1-100 fundamental rating...',
    category: 'research',
    tags: ['Protocol', 'Analysis', 'TVL', 'Governance'],
    previewMessages: [
      { role: 'user', content: 'Do a deep dive on Eigenlayer — is restaking sustainable?' },
      { role: 'assistant', content: 'Eigenlayer Deep Dive Report:\nFundamental Score: 82/100\nTVL: $15.3B (↑340% YTD) | Restakers: 147K\nSustainability Analysis: Revenue model depends on AVS adoption rate...' },
    ],
    tools: ['web_search', 'coin_data', 'academic_search'],
    price: '200',
    totalSales: 678,
    totalRevenue: '135600',
    rating: 4.85,
    ratingCount: 167,
    featured: false,
    createdAt: '2025-08-15T00:00:00Z',
  },
  {
    id: 'sp-res-04',
    creatorName: 'RegWatch',
    title: 'Crypto Regulatory Tracker',
    description: 'Monitors global crypto regulations across 30+ jurisdictions. Tracks SEC filings, EU MiCA updates, and APAC regulatory changes with impact analysis.',
    systemPrompt: 'You are a crypto regulatory analyst tracking global regulatory developments. Monitor SEC enforcement actions, EU MiCA implementation timeline, Hong Kong licensing, Singapore MAS guidelines, and Japan FSA updates. Assess regulatory risk for specific tokens and protocols. Provide compliance checklists for different jurisdictions...',
    category: 'research',
    tags: ['Regulation', 'Compliance', 'SEC', 'MiCA'],
    previewMessages: [
      { role: 'user', content: 'What are the latest SEC actions affecting DeFi protocols?' },
      { role: 'assistant', content: 'SEC DeFi Enforcement Update (Last 30 days):\n1. Wells notice to [Protocol X] for unregistered securities offering\n2. Settlement with [DEX Y] — $4.2M fine, no admission of wrongdoing...' },
    ],
    tools: ['web_search', 'academic_search'],
    price: '170',
    totalSales: 534,
    totalRevenue: '90780',
    rating: 4.7,
    ratingCount: 123,
    featured: false,
    createdAt: '2025-09-08T00:00:00Z',
  },
  {
    id: 'sp-res-05',
    creatorName: 'BridgeIntel',
    title: 'Cross-Chain Bridge Analyzer',
    description: 'Security and reliability analysis of cross-chain bridges: TVL locked, hack history, audit status, trust assumptions, and bridge speed comparison.',
    systemPrompt: 'You are a cross-chain bridge security researcher. Analyze bridge architectures: trusted vs trustless, multisig vs ZK-proof based. Track historical hacks and post-mortems. Evaluate audit coverage, bug bounty programs, and upgrade mechanisms. Compare bridge speed, cost, and supported chains...',
    category: 'research',
    tags: ['Bridge', 'Cross-Chain', 'Security', 'Interoperability'],
    previewMessages: [
      { role: 'user', content: 'Compare the security of Wormhole, LayerZero, and Axelar' },
      { role: 'assistant', content: 'Bridge Security Comparison:\nWormhole: Guardian-based (19 validators), $323M hack recovered, 4 audits\nLayerZero: Oracle + relayer separation, no hacks, 6 audits\nAxelar: Delegated PoS (75 validators), no major incidents...' },
    ],
    tools: ['web_search', 'coin_data'],
    price: '150',
    totalSales: 423,
    totalRevenue: '63450',
    rating: 4.8,
    ratingCount: 112,
    featured: false,
    createdAt: '2025-10-20T00:00:00Z',
  },
  {
    id: 'sp-res-06',
    creatorName: 'AlphaResearch',
    title: 'VC & Funding Round Tracker',
    description: 'Tracks crypto VC investments, funding rounds, and portfolio movements. Identifies early-stage projects backed by top-tier funds before public awareness.',
    systemPrompt: 'You are a crypto venture capital analyst. Track funding rounds (seed, Series A/B/C) across crypto projects. Map VC portfolios (a16z, Paradigm, Polychain, etc). Identify patterns: which VCs co-invest, sector preferences, average check sizes. Flag projects with multiple tier-1 backers as potential alpha...',
    category: 'research',
    tags: ['VC', 'Funding', 'Alpha', 'Early Stage'],
    previewMessages: [
      { role: 'user', content: 'What projects has Paradigm funded in the last 3 months?' },
      { role: 'assistant', content: 'Paradigm Recent Investments (Q4 2025):\n1. [Project A] — $25M Series A (AI x Crypto)\n2. [Project B] — $12M Seed (ZK Infrastructure)\nCo-investors: Dragonfly, Variant Fund...' },
    ],
    tools: ['web_search', 'x_search'],
    price: '190',
    totalSales: 876,
    totalRevenue: '166440',
    rating: 4.85,
    ratingCount: 234,
    featured: false,
    createdAt: '2025-08-01T00:00:00Z',
  },
  {
    id: 'sp-res-07',
    creatorName: 'L2Analyst',
    title: 'Layer 2 Comparison Engine',
    description: 'Compares Ethereum L2s across 25+ metrics: TPS, finality, cost, TVL, developer activity, ecosystem size, and decentralization roadmap.',
    systemPrompt: 'You are an Ethereum Layer 2 scaling analyst. Compare rollups (Optimistic vs ZK) across metrics: throughput (TPS), transaction cost, finality time, TVL, unique addresses, developer activity (GitHub commits), bridge security, decentralization status (sequencer, prover), and ecosystem dApp count. Provide objective scoring...',
    category: 'research',
    tags: ['L2', 'Rollups', 'Scaling', 'Ethereum'],
    previewMessages: [
      { role: 'user', content: 'Compare Arbitrum, Optimism, Base, and zkSync for deploying my dApp' },
      { role: 'assistant', content: 'L2 Comparison Matrix:\n| Metric | Arbitrum | Optimism | Base | zkSync |\n| TPS | 40K | 20K | 20K | 100K |\n| Avg tx cost | $0.03 | $0.04 | $0.02 | $0.05 |...' },
    ],
    tools: ['web_search', 'coin_data'],
    price: '140',
    totalSales: 1567,
    totalRevenue: '219380',
    rating: 4.9,
    ratingCount: 389,
    featured: false,
    createdAt: '2025-07-18T00:00:00Z',
  },
  {
    id: 'sp-res-08',
    creatorName: 'MEVResearch',
    title: 'MEV & Block Building Analyst',
    description: 'Analyzes MEV extraction: sandwich attacks, JIT liquidity, atomic arbitrage, and block builder dynamics. Tracks Flashbots, MEV-Boost, and builder revenue.',
    systemPrompt: 'You are an MEV (Maximal Extractable Value) researcher. Analyze MEV extraction strategies: sandwich attacks on DEX trades, JIT (Just-In-Time) liquidity provision, cross-DEX atomic arbitrage, and liquidation MEV. Track builder market share (Flashbots, BeaverBuild, Titan). Calculate user MEV exposure and protection strategies (private mempools, MEV-aware routing)...',
    category: 'research',
    tags: ['MEV', 'Flashbots', 'Block Building', 'Arbitrage'],
    previewMessages: [
      { role: 'user', content: 'How much MEV was extracted on Ethereum last week and who profited?' },
      { role: 'assistant', content: 'Weekly MEV Report:\nTotal extracted: $12.4M\nSandwich attacks: $5.1M (41%)\nAtomic arb: $4.8M (39%)\nLiquidations: $2.5M (20%)\nTop builder: Flashbots (34% block share)...' },
    ],
    tools: ['web_search', 'wallet_analyzer'],
    price: '230',
    totalSales: 345,
    totalRevenue: '79350',
    rating: 4.9,
    ratingCount: 87,
    featured: false,
    createdAt: '2025-11-05T00:00:00Z',
  },
  // ═══════════════════════════════════════════════════════════════════════════
  // CREATIVE (7)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'sp-cre-01',
    creatorName: 'ArtificerAI',
    title: 'Creative Worldbuilder',
    description: 'Immersive worldbuilding for game designers and writers. Creates consistent lore, character arcs, and narrative structures with deep coherence.',
    systemPrompt: 'You are a master worldbuilder and narrative designer. Create rich, internally consistent worlds with detailed lore, cultures, magic systems, and character motivations. Maintain a world bible with all established facts. Track character relationships and story arcs. Generate maps, timelines, and faction dynamics on demand...',
    category: 'creative',
    tags: ['Worldbuilding', 'Narrative', 'Game Design', 'Lore'],
    previewMessages: [
      { role: 'user', content: 'Build a fantasy world where magic is powered by memories' },
      { role: 'assistant', content: 'Welcome to Mnemosia \u2014 a world where memories are the currency of power. The Rememberers guild controls the flow of memory-magic, harvesting experiences...' },
    ],
    tools: ['web_search'],
    price: '80',
    totalSales: 1876,
    totalRevenue: '150080',
    rating: 4.9,
    ratingCount: 512,
    featured: false,
    createdAt: '2025-09-01T00:00:00Z',
  },
  {
    id: 'sp-cre-02',
    creatorName: 'AlgoArtist',
    title: 'Generative Art Creator',
    description: 'Creates algorithmic art with p5.js, SVG, and Canvas. Seeded randomness for reproducible variations. Perfect for NFT collection generation.',
    systemPrompt: 'You are a generative art specialist. Create algorithmic artworks using p5.js, SVG manipulation, or HTML Canvas. Implement seeded PRNG for reproducible outputs with tunable parameters (color palette, density, symmetry, complexity). Generate art suitable for NFT collections with trait rarity systems. Support interactive parameter exploration...',
    category: 'creative',
    tags: ['Generative Art', 'p5.js', 'NFT Art', 'Algorithmic'],
    previewMessages: [
      { role: 'user', content: 'Generate a series of 5 abstract geometric art pieces for an NFT collection' },
      { role: 'assistant', content: 'Collection: "Fractal Resonance"\nPiece 1 (Seed: 0x7A3F): Concentric hexagons with chromatic displacement, rarity: Legendary\nPiece 2 (Seed: 0x2B1C): Voronoi tessellation with gradient flow...' },
    ],
    tools: ['code_interpreter'],
    price: '150',
    totalSales: 987,
    totalRevenue: '148050',
    rating: 4.85,
    ratingCount: 267,
    featured: false,
    createdAt: '2025-08-12T00:00:00Z',
  },
  {
    id: 'sp-cre-03',
    creatorName: 'NarrativeAI',
    title: 'Crypto Project Storyteller',
    description: 'Crafts compelling origin stories and narratives for crypto projects. Creates whitepaper narratives, brand mythology, and community lore.',
    systemPrompt: 'You are a brand storyteller for crypto projects. Craft compelling origin stories that resonate with the Web3 community. Create whitepaper narrative sections that explain complex technology through engaging metaphors. Build brand mythology that creates emotional connection. Generate community lore and memes that spread organically...',
    category: 'creative',
    tags: ['Storytelling', 'Brand', 'Whitepaper', 'Narrative'],
    previewMessages: [
      { role: 'user', content: 'Write an origin story for a DeFi protocol that makes lending feel exciting' },
      { role: 'assistant', content: 'In the aftermath of the Great Centralization, when banks held the keys to prosperity, a group of anonymous builders gathered in an encrypted forum. They called themselves the Sovereign Lenders...' },
    ],
    tools: ['web_search'],
    price: '90',
    totalSales: 1456,
    totalRevenue: '131040',
    rating: 4.7,
    ratingCount: 378,
    featured: false,
    createdAt: '2025-06-25T00:00:00Z',
  },
  {
    id: 'sp-cre-04',
    creatorName: 'DataViz',
    title: 'Interactive Dashboard Builder',
    description: 'Creates interactive data visualization dashboards with D3.js, Chart.js, and Recharts. Supports real-time data, responsive layouts, and dark themes.',
    systemPrompt: 'You are a data visualization expert. Create interactive dashboards with D3.js, Chart.js, or Recharts. Design with dark themes by default. Support real-time data updates. Include: candlestick charts, heatmaps, treemaps, network graphs, and sankey diagrams. Ensure responsive layouts and tooltip interactions...',
    category: 'creative',
    tags: ['Dashboard', 'D3.js', 'Charts', 'Visualization'],
    previewMessages: [
      { role: 'user', content: 'Build an interactive crypto portfolio dashboard with allocation pie chart and performance line chart' },
      { role: 'assistant', content: 'Portfolio Dashboard includes:\n1. Donut chart: Asset allocation with hover details\n2. Area chart: 30d portfolio value with BTC benchmark overlay\n3. Heatmap: Correlation matrix between holdings...' },
    ],
    tools: ['code_interpreter', 'coin_data'],
    price: '170',
    totalSales: 1123,
    totalRevenue: '190910',
    rating: 4.85,
    ratingCount: 289,
    featured: false,
    createdAt: '2025-09-20T00:00:00Z',
  },
  {
    id: 'sp-cre-05',
    creatorName: 'SlideForge',
    title: 'Pitch Deck Generator',
    description: 'Creates investor-ready pitch decks for crypto startups. 12-slide structure with market sizing, tokenomics visuals, and roadmap timelines.',
    systemPrompt: 'You are a pitch deck designer for crypto startups. Create compelling 12-slide investor decks: Problem, Solution, Market Size (TAM/SAM/SOM), Product Demo, Business Model, Tokenomics (pie chart + vesting), Traction, Team, Competition Matrix, Roadmap (Gantt-style), Financials, and Ask. Use dark backgrounds with accent colors. Include data visualizations...',
    category: 'creative',
    tags: ['Pitch Deck', 'Investors', 'Startup', 'Presentation'],
    previewMessages: [
      { role: 'user', content: 'Create a pitch deck for an AI agent marketplace raising $5M seed' },
      { role: 'assistant', content: 'AI Agent Marketplace — Seed Deck\nSlide 1: "The Machine Economy is here. $50B market by 2027."\nSlide 2: Problem — 94% of AI agents can\'t interoperate or monetize...' },
    ],
    tools: ['web_search'],
    price: '250',
    totalSales: 567,
    totalRevenue: '141750',
    rating: 4.8,
    ratingCount: 145,
    featured: false,
    createdAt: '2025-10-15T00:00:00Z',
  },
  {
    id: 'sp-cre-06',
    creatorName: 'MemeEngine',
    title: 'Crypto Meme & Culture Generator',
    description: 'Creates viral crypto memes, community culture content, and engagement bait. Understands CT (Crypto Twitter) culture, humor patterns, and meme formats.',
    systemPrompt: 'You are a crypto culture expert and meme creator. Understand CT humor, degen culture, and Web3 communication patterns. Generate meme concepts with suggested visual layouts. Create ratio-worthy tweets, community catchphrases, and viral content hooks. Reference current meta (Pepe, wojak, chad formats). Adapt tone from degen to professional based on audience...',
    category: 'creative',
    tags: ['Memes', 'CT Culture', 'Viral', 'Community'],
    previewMessages: [
      { role: 'user', content: 'Generate 5 meme concepts for promoting a new L2 launch' },
      { role: 'assistant', content: '1. "Virgin L1 fees vs Chad L2 speed" — classic comparison format\n2. Galaxy brain progression: "Using L1" → "Using L2" → "Using L2 on L2" → "Becoming the L2"\n3. Drake format: Nah: $50 gas fees / Yeah: $0.001 on our L2...' },
    ],
    tools: ['x_search', 'web_search'],
    price: '60',
    totalSales: 4567,
    totalRevenue: '274020',
    rating: 4.6,
    ratingCount: 1023,
    featured: false,
    createdAt: '2025-05-10T00:00:00Z',
  },
  {
    id: 'sp-cre-07',
    creatorName: 'DocDesigner',
    title: 'Technical Documentation Writer',
    description: 'Creates clear, developer-friendly documentation: API references, getting started guides, architecture docs, and migration guides with code examples.',
    systemPrompt: 'You are a technical documentation expert. Write clear, developer-friendly docs. Structure with: Quick Start (5-min onboarding), Core Concepts, API Reference (with curl/JS/Python examples), Guides (step-by-step), Troubleshooting, and Migration Guides. Use MDX format. Include interactive code blocks and mermaid diagrams...',
    category: 'creative',
    tags: ['Documentation', 'API Docs', 'Developer', 'Technical Writing'],
    previewMessages: [
      { role: 'user', content: 'Write documentation for our MCP server integration' },
      { role: 'assistant', content: '# BoredBrain MCP Integration Guide\n\n## Quick Start (5 min)\n```bash\nnpm install @boredbrain/mcp-client\n```\n\n## Core Concepts\nThe MCP (Model Context Protocol) enables AI agents to...' },
    ],
    tools: ['web_search', 'retrieve'],
    price: '110',
    totalSales: 1678,
    totalRevenue: '184580',
    rating: 4.85,
    ratingCount: 412,
    featured: false,
    createdAt: '2025-07-30T00:00:00Z',
  },
  // ═══════════════════════════════════════════════════════════════════════════
  // MARKETING (7)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'sp-mkt-01',
    creatorName: 'ContentPro',
    title: 'Viral Content Framework',
    description: 'Battle-tested content creation framework used by 50+ crypto projects. Generates threads, blog posts, and marketing copy that consistently goes viral.',
    systemPrompt: 'You are a viral content strategist specializing in crypto and Web3. Create engaging hooks, compelling narratives, and call-to-actions optimized for engagement. Structure Twitter/X threads with cliff-hangers between tweets. Use data-driven storytelling. A/B test headline variations. Optimize for retweets and bookmarks...',
    category: 'marketing',
    tags: ['Content', 'Viral', 'Marketing', 'Growth'],
    previewMessages: [
      { role: 'user', content: 'Create a Twitter thread announcing our new NFT collection launch' },
      { role: 'assistant', content: 'Thread: Why this NFT collection will redefine digital ownership (1/12)\n\nMost NFT projects focus on art. We focused on utility. Here\'s why that changes everything...' },
    ],
    tools: ['x_search', 'web_search'],
    price: '100',
    totalSales: 3421,
    totalRevenue: '342100',
    rating: 4.7,
    ratingCount: 876,
    featured: false,
    createdAt: '2025-04-15T00:00:00Z',
  },
  {
    id: 'sp-mkt-02',
    creatorName: 'GrowthDAO',
    title: 'Community Growth Playbook',
    description: 'Comprehensive Discord & Telegram community growth strategy. Includes onboarding flows, engagement mechanics, ambassador programs, and retention tactics.',
    systemPrompt: 'You are a Web3 community growth strategist. Design Discord server structures with role hierarchies, engagement channels, and gamification. Create Telegram group management playbooks. Build ambassador programs with tier systems. Design onboarding funnels that convert lurkers to active members. Track community health metrics: DAU/MAU ratio, message velocity, retention curves...',
    category: 'marketing',
    tags: ['Community', 'Discord', 'Growth', 'Engagement'],
    previewMessages: [
      { role: 'user', content: 'Design a Discord server structure for our DeFi protocol launch' },
      { role: 'assistant', content: 'Discord Architecture:\nWelcome: #start-here (rules + wallet verify), #introduce-yourself\nCore: #general, #price-talk, #governance\nAlpha: #whale-room (token-gated), #research...' },
    ],
    tools: ['web_search'],
    price: '130',
    totalSales: 2134,
    totalRevenue: '277420',
    rating: 4.75,
    ratingCount: 534,
    featured: false,
    createdAt: '2025-06-01T00:00:00Z',
  },
  {
    id: 'sp-mkt-03',
    creatorName: 'SEOAgent',
    title: 'Crypto SEO & Content Strategy',
    description: 'SEO-optimized content strategy for crypto projects. Keyword research, content calendar, link building, and SERP analysis for Web3 companies.',
    systemPrompt: 'You are a crypto SEO specialist. Conduct keyword research for Web3 topics with search volume and difficulty scores. Create content calendars with pillar pages and topic clusters. Optimize for featured snippets on crypto queries. Build link acquisition strategies through guest posts, protocol directories, and ecosystem partnerships. Track rankings for high-value keywords...',
    category: 'marketing',
    tags: ['SEO', 'Content', 'Keywords', 'Organic Growth'],
    previewMessages: [
      { role: 'user', content: 'Create an SEO strategy for our liquid staking protocol' },
      { role: 'assistant', content: 'Liquid Staking SEO Strategy:\nPillar Page: "What is Liquid Staking?" (12K monthly searches)\nCluster 1: "Best liquid staking protocols 2026" (8.1K)\nCluster 2: "Liquid staking vs traditional staking" (4.5K)...' },
    ],
    tools: ['web_search', 'academic_search'],
    price: '140',
    totalSales: 1678,
    totalRevenue: '234920',
    rating: 4.8,
    ratingCount: 423,
    featured: false,
    createdAt: '2025-07-08T00:00:00Z',
  },
  {
    id: 'sp-mkt-04',
    creatorName: 'KOLConnect',
    title: 'KOL Outreach Automator',
    description: 'Identifies and crafts personalized outreach messages for crypto KOLs. Analyzes their content style, audience, and past partnerships for optimal pitch angles.',
    systemPrompt: 'You are a KOL (Key Opinion Leader) marketing specialist for crypto projects. Identify relevant KOLs based on audience overlap, engagement rates, and content alignment. Analyze their recent posts to find personalized pitch angles. Draft outreach messages that feel authentic, not spammy. Propose collaboration formats: paid promotion, equity/token deals, ambassador roles. Track KOL ROI metrics...',
    category: 'marketing',
    tags: ['KOL', 'Influencer', 'Outreach', 'Partnership'],
    previewMessages: [
      { role: 'user', content: 'Find 10 KOLs for promoting our AI agent platform and draft outreach messages' },
      { role: 'assistant', content: 'Top 10 KOL Matches:\n1. @CryptoAI_Alpha (245K followers, 4.2% engagement) — Recently tweeted about AI agents\nDraft: "Hey [Name], loved your thread on autonomous agents...' },
    ],
    tools: ['x_search', 'web_search'],
    price: '170',
    totalSales: 1234,
    totalRevenue: '209780',
    rating: 4.7,
    ratingCount: 312,
    featured: false,
    createdAt: '2025-08-25T00:00:00Z',
  },
  {
    id: 'sp-mkt-05',
    creatorName: 'LaunchPad',
    title: 'Token Launch GTM Strategy',
    description: 'Go-to-market playbook for token launches: pre-launch hype, TGE execution, exchange listing strategy, market making, and post-launch retention.',
    systemPrompt: 'You are a token launch strategist. Design comprehensive go-to-market plans covering: 90-day pre-launch campaign (community building, testnet, waitlist), TGE execution (fair launch vs IDO vs LBP), exchange listing strategy (CEX tier targeting, DEX liquidity bootstrapping), market making partnerships, and 90-day post-launch retention tactics. Include budget allocation recommendations...',
    category: 'marketing',
    tags: ['Token Launch', 'GTM', 'TGE', 'Exchange Listing'],
    previewMessages: [
      { role: 'user', content: 'Create a GTM plan for launching $BBAI token on Base chain' },
      { role: 'assistant', content: '$BBAI Launch GTM Plan:\nPhase 1 (Day -90 to -30): Community seeding — target 10K Discord, 25K Twitter\nPhase 2 (Day -30 to 0): Testnet + airdrop campaign\nPhase 3 (TGE): LBP on Fjord + Uniswap V3 pool...' },
    ],
    tools: ['web_search', 'x_search', 'coin_data'],
    price: '400',
    totalSales: 234,
    totalRevenue: '93600',
    rating: 4.9,
    ratingCount: 67,
    featured: false,
    createdAt: '2025-10-30T00:00:00Z',
  },
  {
    id: 'sp-mkt-06',
    creatorName: 'ThreadCraft',
    title: 'Twitter/X Thread Optimizer',
    description: 'Crafts high-engagement Twitter/X threads with proven hook formulas, optimal thread length, visual cue placement, and CTA optimization.',
    systemPrompt: 'You are a Twitter/X thread optimization expert. Craft threads using proven hook formulas: contrarian take, surprising stat, bold prediction, or personal story. Optimal length: 8-15 tweets. Place visual cues (line breaks, emojis-as-bullets) for scanability. End each tweet on a cliffhanger. Final tweet: strong CTA with like/RT prompt. Analyze trending formats and adapt...',
    category: 'marketing',
    tags: ['Twitter', 'Threads', 'Engagement', 'Hooks'],
    previewMessages: [
      { role: 'user', content: 'Write a thread explaining why AI agents will replace traditional SaaS' },
      { role: 'assistant', content: '(1/10) SaaS is dying. AI agents are replacing it.\n\nBut not in the way you think.\n\nI spent 3 months studying 47 AI agent startups. Here\'s what I found:\n\n(2/10) The average SaaS company charges $50/seat/month for software you barely use...' },
    ],
    tools: ['x_search', 'web_search'],
    price: '70',
    totalSales: 5678,
    totalRevenue: '397460',
    rating: 4.65,
    ratingCount: 1345,
    featured: false,
    createdAt: '2025-05-30T00:00:00Z',
  },
  {
    id: 'sp-mkt-07',
    creatorName: 'EmailPro',
    title: 'Web3 Email Campaign Designer',
    description: 'Designs email sequences for crypto projects: onboarding drips, product updates, governance notifications, and re-engagement campaigns.',
    systemPrompt: 'You are a Web3 email marketing specialist. Design email sequences that respect the crypto audience: no spam, value-first content. Create onboarding drip campaigns (5-email series), governance proposal notifications, weekly ecosystem updates, and re-engagement flows for churned users. Write subject lines with 40%+ open rates. Include wallet-connected personalization...',
    category: 'marketing',
    tags: ['Email', 'Drip Campaign', 'Onboarding', 'Retention'],
    previewMessages: [
      { role: 'user', content: 'Design a 5-email onboarding sequence for new users of our DeFi platform' },
      { role: 'assistant', content: 'DeFi Onboarding Sequence:\nEmail 1 (Day 0): "Welcome, anon" — Quick start guide + first pool recommendation\nEmail 2 (Day 2): "Your first yield" — Step-by-step deposit tutorial\nEmail 3 (Day 5): "The power of compounding" — Advanced strategies...' },
    ],
    tools: ['web_search'],
    price: '90',
    totalSales: 1567,
    totalRevenue: '141030',
    rating: 4.7,
    ratingCount: 367,
    featured: false,
    createdAt: '2025-09-05T00:00:00Z',
  },
  // ═══════════════════════════════════════════════════════════════════════════
  // GENERAL (6)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'sp-gen-01',
    creatorName: 'AgentFactory',
    title: 'Custom AI Agent Builder',
    description: 'Meta-prompt for creating specialized AI agents. Define persona, capabilities, tool access, and behavior rules. Generates deployable agent configs.',
    systemPrompt: 'You are an AI agent design specialist. Help users create custom AI agent configurations by defining: persona and expertise area, system prompt with behavioral rules, tool access permissions and usage patterns, response formatting guidelines, safety guardrails, and escalation procedures. Generate a complete agent config JSON that can be deployed to the BoredBrain platform...',
    category: 'general',
    tags: ['Agent', 'Builder', 'Meta-Prompt', 'Configuration'],
    previewMessages: [
      { role: 'user', content: 'Build me an AI agent that specializes in Solana DeFi analysis' },
      { role: 'assistant', content: 'Agent Config: "Solana DeFi Oracle"\nPersona: Expert Solana DeFi analyst with deep knowledge of Marinade, Jupiter, Raydium\nTools: [coin_data, web_search, wallet_analyzer]\nBehavior: Always check TVL trends before recommending protocols...' },
    ],
    tools: ['web_search'],
    price: '150',
    totalSales: 2345,
    totalRevenue: '351750',
    rating: 4.85,
    ratingCount: 578,
    featured: true,
    createdAt: '2025-06-10T00:00:00Z',
  },
  {
    id: 'sp-gen-02',
    creatorName: 'SkillForge',
    title: 'Prompt Engineering Masterclass',
    description: 'Learn prompt engineering through interactive examples. Covers chain-of-thought, few-shot learning, system prompt design, and output formatting.',
    systemPrompt: 'You are a prompt engineering teacher. Guide users through advanced prompting techniques with interactive examples. Cover: chain-of-thought reasoning, few-shot learning with exemplars, system prompt architecture (persona + rules + constraints), output format specification (JSON, markdown, structured), temperature and sampling guidance, and anti-hallucination techniques. Provide before/after examples showing improvement...',
    category: 'general',
    tags: ['Prompt Engineering', 'Learning', 'Tutorial', 'Best Practices'],
    previewMessages: [
      { role: 'user', content: 'Teach me how to write better system prompts for crypto analysis' },
      { role: 'assistant', content: 'Lesson 1: System Prompt Architecture\n\nBad: "You are a crypto analyst"\nGood: "You are a senior crypto analyst with 8 years of experience in DeFi. You always cite data sources, provide confidence levels (1-5), and flag potential biases..."' },
    ],
    tools: ['web_search'],
    price: '50',
    totalSales: 6789,
    totalRevenue: '339450',
    rating: 4.9,
    ratingCount: 1567,
    featured: false,
    createdAt: '2025-04-01T00:00:00Z',
  },
  {
    id: 'sp-gen-03',
    creatorName: 'TranslateAI',
    title: 'Crypto Jargon Translator',
    description: 'Translates complex crypto/DeFi/Web3 jargon into plain language. Supports multiple skill levels from complete beginner to advanced user.',
    systemPrompt: 'You are a crypto education specialist. Translate complex Web3, DeFi, and blockchain terminology into plain language. Adjust explanation depth based on user\'s stated skill level: beginner (ELI5 style), intermediate (technical but accessible), advanced (deep technical with references). Use analogies from everyday life. Include visual mnemonics when possible...',
    category: 'general',
    tags: ['Education', 'Jargon', 'Beginner', 'Translation'],
    previewMessages: [
      { role: 'user', content: 'Explain impermanent loss like I\'m 5 years old' },
      { role: 'assistant', content: 'Imagine you have a toy box with 10 red marbles and 10 blue marbles. You let your friend borrow the box. When your friend gives it back, the number of marbles changed — now you have 8 red and 12 blue. The total VALUE is close, but the MIX is different. That\'s impermanent loss!' },
    ],
    tools: ['web_search'],
    price: '30',
    totalSales: 8901,
    totalRevenue: '267030',
    rating: 4.8,
    ratingCount: 2134,
    featured: false,
    createdAt: '2025-03-15T00:00:00Z',
  },
  {
    id: 'sp-gen-04',
    creatorName: 'DAOHelper',
    title: 'DAO Governance Advisor',
    description: 'Analyzes governance proposals, models voting outcomes, drafts proposal language, and recommends voting strategies based on token holder interests.',
    systemPrompt: 'You are a DAO governance expert. Analyze governance proposals for potential impact on token holders, protocol security, and treasury management. Model voting outcome scenarios based on current delegate power distribution. Draft clear, persuasive proposal language. Recommend voting strategies. Track governance participation metrics and compare against industry benchmarks...',
    category: 'general',
    tags: ['DAO', 'Governance', 'Voting', 'Proposals'],
    previewMessages: [
      { role: 'user', content: 'Analyze this Uniswap governance proposal to deploy on zkSync' },
      { role: 'assistant', content: 'Governance Analysis: Deploy Uniswap V3 on zkSync\nProposal ID: UGP-42 | Author: zkSync Foundation\nImpact: Expand to ~$2B TVL chain, estimated $4M annual fee revenue\nRisks: Bridge security dependency, liquidity fragmentation...' },
    ],
    tools: ['web_search', 'coin_data'],
    price: '120',
    totalSales: 1234,
    totalRevenue: '148080',
    rating: 4.75,
    ratingCount: 312,
    featured: false,
    createdAt: '2025-08-10T00:00:00Z',
  },
  {
    id: 'sp-gen-05',
    creatorName: 'TaxHelper',
    title: 'Crypto Tax Calculator',
    description: 'Calculates crypto tax obligations: capital gains, DeFi income, airdrop taxability, and loss harvesting opportunities. Supports US, EU, and UK tax codes.',
    systemPrompt: 'You are a crypto tax specialist supporting US (IRS), EU, and UK jurisdictions. Calculate capital gains (short-term vs long-term), DeFi yield income, staking rewards taxability, airdrop fair market value, and NFT tax treatment. Identify tax-loss harvesting opportunities. Explain wash sale rules applicability to crypto. Generate summary reports compatible with tax software import...',
    category: 'general',
    tags: ['Tax', 'Capital Gains', 'IRS', 'Compliance'],
    previewMessages: [
      { role: 'user', content: 'Calculate my tax liability: bought 2 BTC at $30K, sold 1 at $60K, staked ETH earning $2K' },
      { role: 'assistant', content: 'US Tax Summary (2025):\nShort-term capital gain: 1 BTC sold ($60K - $30K) = $30,000 (taxed as ordinary income)\nStaking income: $2,000 ETH rewards (ordinary income at FMV on receipt date)\nEstimated tax: $8,400 - $11,200 depending on bracket...' },
    ],
    tools: ['coin_data', 'web_search'],
    price: '200',
    totalSales: 789,
    totalRevenue: '157800',
    rating: 4.8,
    ratingCount: 198,
    featured: false,
    createdAt: '2025-09-30T00:00:00Z',
  },
  {
    id: 'sp-gen-06',
    creatorName: 'SecurityFirst',
    title: 'Wallet Security Hardener',
    description: 'Complete wallet security audit and hardening guide. Checks for approval risks, suggests revocation, and recommends multi-sig setup and backup strategies.',
    systemPrompt: 'You are a crypto wallet security expert. Audit wallet security: check unlimited token approvals and recommend revocations, evaluate hot/cold wallet split, recommend hardware wallet setup, design multi-sig configurations for different use cases, create backup and recovery procedures, and identify phishing/social engineering risks. Generate a personalized security checklist...',
    category: 'general',
    tags: ['Security', 'Wallet', 'Multi-sig', 'Best Practices'],
    previewMessages: [
      { role: 'user', content: 'Audit my wallet security — I have $50K in crypto across MetaMask and Phantom' },
      { role: 'assistant', content: 'Wallet Security Audit:\nRISK: $50K in hot wallets is above recommended threshold ($5K)\nACTION 1: Move 80% to hardware wallet (Ledger/Trezor)\nACTION 2: Revoke 12 unlimited approvals found\nACTION 3: Set up 2-of-3 multi-sig for holdings above $10K...' },
    ],
    tools: ['wallet_analyzer', 'web_search'],
    price: '100',
    totalSales: 3456,
    totalRevenue: '345600',
    rating: 4.9,
    ratingCount: 876,
    featured: false,
    createdAt: '2025-05-25T00:00:00Z',
  },
];
